Repository jellyfin/jellyfin, pull requests merged in 2018-12, with the labels that each got.

#132 Add maxcpucount to dotnet clean
  debian/rules
Labels: bug, build/platform

#193 Debian packaging improvements
  debian/changelog
  debian/control
  debian/preinst
Labels: build/platform

#238 Restore the name Emby in manifest.json
  MediaBrowser.WebDashboard/dashboard-ui/manifest.json
Labels: UI, bug

#288 Remove custom ToArray extension
  Emby.Dlna/ContentDirectory/ControlHandler.cs
  Emby.Dlna/Didl/DidlBuilder.cs
  Emby.Dlna/PlayTo/Device.cs
  Emby.Dlna/PlayTo/PlayToController.cs
  Emby.Dlna/Profiles/DefaultProfile.cs
  Emby.Dlna/Service/BaseControlHandler.cs
  Emby.Drawing/ImageProcessor.cs
  Emby.Server.Implementations/Activity/ActivityLogEntryPoint.cs
  Emby.Server.Implementations/Activity/ActivityRepository.cs
  Emby.Server.Implementations/ApplicationHost.cs
  Emby.Server.Implementations/Channels/ChannelManager.cs
  Emby.Server.Implementations/Collections/CollectionManager.cs
  Emby.Server.Implementations/Data/SqliteItemRepository.cs
  Emby.Server.Implementations/Devices/DeviceManager.cs
  Emby.Server.Implementations/Dto/DtoService.cs
  Emby.Server.Implementations/EntryPoints/ExternalPortForwarding.cs
  Emby.Server.Implementations/EntryPoints/UsageEntryPoint.cs
  Emby.Server.Implementations/HttpServer/HttpListenerHost.cs
  Emby.Server.Implementations/IO/SharpCifs/Util/Sharpen/Collections.cs
  Emby.Server.Implementations/Library/LibraryManager.cs
  Emby.Server.Implementations/Library/SearchEngine.cs
  Emby.Server.Implementations/Library/UserViewManager.cs
  Emby.Server.Implementations/LiveTv/LiveTvDtoService.cs
  Emby.Server.Implementations/LiveTv/LiveTvManager.cs
  Emby.Server.Implementations/LiveTv/LiveTvMediaSourceProvider.cs
  Emby.Server.Implementations/Networking/NetworkManager.cs
  Emby.Server.Implementations/Playlists/PlaylistManager.cs
  Emby.Server.Implementations/ScheduledTasks/ChapterImagesTask.cs
  Emby.Server.Implementations/ScheduledTasks/ScheduledTaskWorker.cs
  Emby.Server.Implementations/Security/AuthenticationRepository.cs
  Emby.Server.Implementations/Services/ServiceExec.cs
  Emby.Server.Implementations/Services/ServicePath.cs
  Emby.Server.Implementations/Session/SessionManager.cs
  MediaBrowser.Api/BaseApiService.cs
  MediaBrowser.Api/LiveTv/LiveTvService.cs
  MediaBrowser.Api/Movies/MoviesService.cs
  MediaBrowser.Api/SimilarItemsHelper.cs
  MediaBrowser.Api/UserLibrary/BaseItemsByNameService.cs
  MediaBrowser.Api/UserLibrary/UserViewsService.cs
  MediaBrowser.Controller/Entities/BaseItem.cs
  MediaBrowser.Controller/Entities/CollectionFolder.cs
  MediaBrowser.Controller/Entities/Extensions.cs
  MediaBrowser.Controller/Entities/Folder.cs
  MediaBrowser.Controller/Entities/TagExtensions.cs
  MediaBrowser.LocalMetadata/Parsers/BoxSetXmlParser.cs
  MediaBrowser.LocalMetadata/Parsers/PlaylistXmlParser.cs
  MediaBrowser.Model/Dlna/MediaFormatProfileResolver.cs
  MediaBrowser.Model/Dlna/StreamInfo.cs
  MediaBrowser.Model/Entities/MediaStream.cs
  MediaBrowser.Model/Extensions/LinqExtensions.cs
  MediaBrowser.Model/Services/HttpUtility.cs
  MediaBrowser.Model/Services/QueryParamCollection.cs
  MediaBrowser.Providers/Manager/ImageSaver.cs
  MediaBrowser.Providers/Manager/ProviderManager.cs
  MediaBrowser.Providers/Movies/GenericMovieDbInfo.cs
  MediaBrowser.Providers/Movies/MovieDbProvider.cs
  MediaBrowser.Providers/Music/MusicBrainzAlbumProvider.cs
  MediaBrowser.Providers/TV/TheMovieDb/MovieDbSeriesProvider.cs
  Mono.Nat/Pmp/PmpNatDevice.cs
Labels: Backend

#304 Add new file header to use as a base for new files
  new-file-header.txt
Labels: fork

#323 Add merge=union for CONTRIBUTORS.md
  .gitattributes
Labels: documentation
