Repository jellyfin/jellyfin, pull requests merged in 2019-03, with the labels that each got.

#947 Add Azure Pipelines YAML
  .ci/azure-pipelines.yml
  README.md
Labels: build/platform

#870 Better default authentication
  Emby.Server.Implementations/Cryptography/CryptographyProvider.cs
  Emby.Server.Implementations/Data/SqliteUserRepository.cs
  Emby.Server.Implementations/Library/DefaultAuthenticationProvider.cs
  Emby.Server.Implementations/Library/UserManager.cs
  MediaBrowser.Model/Cryptography/ICryptoProvider.cs
  MediaBrowser.Model/Cryptography/PasswordHash.cs
Labels: backend, feature

#1091 Do not use the nuget packages for comparison, but the last master build
  .ci/azure-pipelines.yml
Labels: help wanted
