Repository jellyfin/jellyfin, pull requests merged in 2019-12, with the labels that each got.

#2104 Simplify regex to avoid catastrophic backtracking
  Emby.Naming/Common/NamingOptions.cs
Labels: stable-backport

#2158 Remove broken Microsoft SDK image
  deployment/ubuntu-package-x64/Dockerfile
Labels: build/platform

#1941 Make probesize and analyzeduration configurable and simplify circular dependencies
  Emby.Server.Implementations/ApplicationHost.cs
  Emby.Server.Implementations/ConfigurationOptions.cs
  Emby.Server.Implementations/Emby.Server.Implementations.csproj
  Jellyfin.Server/Program.cs
  MediaBrowser.Api/Playback/BaseStreamingService.cs
  MediaBrowser.Api/Playback/Hls/BaseHlsService.cs
  MediaBrowser.Api/Playback/Hls/DynamicHlsService.cs
  MediaBrowser.Api/Playback/Hls/VideoHlsService.cs
  MediaBrowser.Api/Playback/Progressive/AudioService.cs
  MediaBrowser.Api/Playback/Progressive/BaseProgressiveStreamingService.cs
  MediaBrowser.Api/Playback/Progressive/VideoService.cs
  MediaBrowser.Api/Playback/UniversalAudioService.cs
  MediaBrowser.Controller/Entities/Video.cs
  MediaBrowser.Controller/Extensions/ConfigurationExtensions.cs
  MediaBrowser.Controller/MediaBrowser.Controller.csproj
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.Controller/MediaEncoding/IMediaEncoder.cs
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
  MediaBrowser.MediaEncoding/Subtitles/ISubtitleWriter.cs
  MediaBrowser.MediaEncoding/Subtitles/JsonWriter.cs
  MediaBrowser.MediaEncoding/Subtitles/SrtWriter.cs
  MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
  MediaBrowser.MediaEncoding/Subtitles/TtmlWriter.cs
  MediaBrowser.Model/Configuration/ServerConfiguration.cs
  MediaBrowser.Model/MediaInfo/SubtitleTrackInfo.cs
  MediaBrowser.Providers/MediaInfo/VideoImageProvider.cs
Labels: Breaks Plugin API
