Repository jellyfin/jellyfin, pull requests merged in 2019-01, with the labels that each got.

#286 Clean up HttpClientManager, LiveTvManager and InstallationManager
  Emby.Server.Implementations/ApplicationHost.cs
  Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs
  Emby.Server.Implementations/LiveTv/Listings/SchedulesDirect.cs
  Emby.Server.Implementations/LiveTv/LiveTvManager.cs
  Emby.Server.Implementations/Updates/InstallationManager.cs
  MediaBrowser.Common/Net/IHttpClient.cs
  MediaBrowser.Providers/Movies/MovieDbProvider.cs
Labels: Backend

#385 Don't send usage to emby
  Emby.Server.Implementations/EntryPoints/UsageEntryPoint.cs
  Emby.Server.Implementations/EntryPoints/UsageReporter.cs
  MediaBrowser.Model/Configuration/ServerConfiguration.cs
  MediaBrowser.WebDashboard/dashboard-ui/dashboard/dashboardgeneral.js
Labels: Backend

#381 Emby.Drawing.Skia remove deprecated functions.
  Emby.Drawing.Skia/SkiaEncoder.cs
  Emby.Drawing.Skia/StripCollageBuilder.cs
Labels: Backend

#383 Remove firebase and empty resource config file
  Emby.Server.Implementations/ApplicationHost.cs
  Emby.Server.Implementations/Session/FirebaseSessionController.cs
  Emby.Server.Implementations/Session/SessionManager.cs
  MediaBrowser.Common/IApplicationHost.cs
  MediaBrowser.Model/Session/ClientCapabilities.cs
  MediaBrowser.Providers/Music/MusicBrainzAlbumProvider.cs
  MediaBrowser.Providers/Omdb/OmdbProvider.cs
Labels: Backend

#390 Remove remaining part old logging code
  Emby.Server.Implementations/ApplicationHost.cs
Labels: Backend, enhancement

#444 Update shared version to 10.0.0
  SharedVersion.cs
Labels: build/platform

#307 Fix transcoding of AAC from 5.1 to stereo to support Chromecast
  MediaBrowser.Api/Playback/BaseStreamingService.cs
Labels: requires testing

#440 Debian packaging for 10.0.0
  .gitignore
  debian/changelog
  debian/conf/jellyfin
  debian/conf/logging.json
  debian/control
  debian/install
  debian/jellyfin.service
  debian/postinst
  debian/postrm
  debian/preinst
  debian/prerm
Labels: build/platform

#447 Update readme to use readthedocs and clean up
  README.md
Labels: WIP, documentation

#382 Codestyle EditorConfig file added.
  .editorconfig
Labels: fork, question

#435 Reduce log spam from ffmpeg info
  MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
Labels: Backend, requires testing

#487 Support `*.log` files in browser log viewer
  MediaBrowser.Model/Net/MimeTypes.cs
Labels: Backend

#524 Master 10.0.1
  CONTRIBUTORS.md
  Emby.Drawing/Common/ImageHeader.cs
  Emby.Server.Implementations/Emby.Server.Implementations.csproj
  Emby.Server.Implementations/LiveTv/LiveTvManager.cs
  Emby.Server.Implementations/ScheduledTasks/Tasks/DeleteLogFileTask.cs
  Emby.Server.Implementations/values.txt
  MediaBrowser.Common/MediaBrowser.Common.csproj
  MediaBrowser.Controller/Entities/Movies/BoxSet.cs
  MediaBrowser.Controller/Entities/Movies/Movie.cs
  MediaBrowser.Controller/Entities/TV/Episode.cs
  MediaBrowser.Controller/Entities/Trailer.cs
  MediaBrowser.Controller/LiveTv/LiveTvProgram.cs
  MediaBrowser.Controller/MediaBrowser.Controller.csproj
  MediaBrowser.Model/MediaBrowser.Model.csproj
  MediaBrowser.Model/Net/MimeTypes.cs
  MediaBrowser.WebDashboard/dashboard-ui/dashboardgeneral.html
  MediaBrowser.WebDashboard/dashboard-ui/scripts/myprofile.js
  SharedVersion.cs
  debian/changelog
Labels: roadmap

#540 Update Emby API keys to our own
  MediaBrowser.Controller/Library/TVUtils.cs
  MediaBrowser.MediaEncoding/Subtitles/OpenSubtitleDownloader.cs
  MediaBrowser.Providers/Movies/FanartMovieImageProvider.cs
  MediaBrowser.Providers/Movies/MovieDbProvider.cs
  MediaBrowser.Providers/Movies/MovieDbSearch.cs
  MediaBrowser.Providers/Music/AudioDbArtistProvider.cs
  MediaBrowser.Providers/Music/FanArtArtistProvider.cs
  MediaBrowser.Providers/Omdb/OmdbImageProvider.cs
  MediaBrowser.Providers/Omdb/OmdbProvider.cs
  MediaBrowser.Providers/TV/FanArt/FanartSeriesProvider.cs
Labels: Backend, fork

#455 Clean up some small things
  Emby.Server.Implementations/ApplicationHost.cs
  Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs
  Emby.Server.Implementations/HttpServer/HttpListenerHost.cs
  Emby.Server.Implementations/HttpServer/HttpResultFactory.cs
  Emby.Server.Implementations/HttpServer/RangeRequestWriter.cs
  Emby.Server.Implementations/HttpServer/ResponseFilter.cs
  Emby.Server.Implementations/Services/HttpResult.cs
  Emby.Server.Implementations/Services/RequestHelper.cs
Labels: cleanup

#534 Add linux-arm and linux-arm64 native NuGet dependency.
  Emby.Drawing.Skia/Emby.Drawing.Skia.csproj
Labels: Backend, build/platform

#613 Update MediaEncoding
  MediaBrowser.Api/Playback/StreamRequest.cs
  MediaBrowser.Api/Playback/StreamState.cs
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.Controller/MediaEncoding/EncodingJobInfo.cs
  MediaBrowser.Controller/MediaEncoding/EncodingJobOptions.cs
  MediaBrowser.MediaEncoding/Encoder/EncodingJob.cs
Labels: Backend, requires testing

#621 Minor improvements to library scan code
  Emby.Naming/TV/EpisodeResolver.cs
  Emby.Naming/Video/StubResolver.cs
  Emby.Naming/Video/StubResult.cs
  Emby.Naming/Video/VideoResolver.cs
  Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs
  Emby.Server.Implementations/IO/ManagedFileSystem.cs
  Emby.Server.Implementations/Library/Resolvers/TV/SeriesResolver.cs
  MediaBrowser.Controller/Entities/BaseItem.cs
  MediaBrowser.Providers/TV/TheMovieDb/MovieDbSeriesProvider.cs
Labels: Backend

#535 Clean up streambuilder
  MediaBrowser.Model/Dlna/AudioOptions.cs
  MediaBrowser.Model/Dlna/ConditionProcessor.cs
  MediaBrowser.Model/Dlna/DeviceProfile.cs
  MediaBrowser.Model/Dlna/StreamBuilder.cs
Labels: cleanup

#689 Fix RPM package build for fedora
  deployment/common.build.sh
  deployment/fedora-package-x64/clean.sh
  deployment/fedora-package-x64/package.sh
Labels: build/platform, requires testing

#452 Use EF Core for Activity database
  Emby.Server.Implementations/Activity/ActivityLogEntryPoint.cs
  Emby.Server.Implementations/Activity/ActivityManager.cs
  Emby.Server.Implementations/Activity/ActivityRepository.cs
  Emby.Server.Implementations/ApplicationHost.cs
  Emby.Server.Implementations/Emby.Server.Implementations.csproj
  Jellyfin.Server/Program.cs
  MediaBrowser.Api/Library/LibraryService.cs
  MediaBrowser.Common/IApplicationHost.cs
  MediaBrowser.Model/Activity/IActivityManager.cs
  MediaBrowser.Model/Activity/IActivityRepository.cs
Labels: requires testing

#721 Change image dimentions from double to int
  Emby.Dlna/Didl/DidlBuilder.cs
  Emby.Drawing/ImageProcessor.cs
  Emby.Drawing/NullImageEncoder.cs
  Emby.Drawing/PercentPlayedDrawer.cs
  Emby.Drawing/PlayedIndicatorDrawer.cs
  Emby.Drawing/SkiaEncoder.cs
  Emby.Drawing/UnplayedCountIndicator.cs
  Emby.Photos/PhotoProvider.cs
  Emby.Server.Implementations/Dto/DtoService.cs
  MediaBrowser.Api/Images/ImageService.cs
  MediaBrowser.Controller/Drawing/IImageEncoder.cs
  MediaBrowser.Controller/Drawing/IImageProcessor.cs
  MediaBrowser.Controller/Drawing/ImageHelper.cs
  MediaBrowser.Controller/Drawing/ImageProcessingOptions.cs
  MediaBrowser.Controller/Entities/BaseItem.cs
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.Controller/MediaEncoding/EncodingJobInfo.cs
  MediaBrowser.Controller/Providers/IImageEnhancer.cs
  MediaBrowser.Model/Dlna/StreamInfo.cs
  MediaBrowser.Model/Drawing/DrawingUtils.cs
  MediaBrowser.Model/Drawing/ImageSize.cs
Labels: requires testing

#739 Change multi version logic for movies
  Emby.Naming/Video/VideoListResolver.cs
Labels: requires testing

#716 Remove more compile time warnings
  Emby.Server.Implementations/Activity/ActivityLogEntryPoint.cs
  Emby.Server.Implementations/ApplicationHost.cs
  MediaBrowser.Api/PluginService.cs
  MediaBrowser.Api/UserLibrary/PlaystateService.cs
  MediaBrowser.Controller/Subtitles/ISubtitleManager.cs
  MediaBrowser.Providers/Subtitles/SubtitleManager.cs
Labels: requires testing
