Repository jellyfin/jellyfin, pull requests merged in 2019-11, with the labels that each got.

#1859 Fix COPR build and Fedora packaging
  .copr/Makefile
  deployment/centos-package-x64/Dockerfile
  deployment/centos-package-x64/docker-build.sh
  deployment/fedora-package-x64/Dockerfile
  deployment/fedora-package-x64/docker-build.sh
  deployment/fedora-package-x64/pkg-src/jellyfin.spec
Labels: stable-backport

#1904 Switch ffmpeg to hls muxer (from segment) to fix premature stop on non-patched ffmpeg
  Emby.Server.Implementations/HttpServer/HttpListenerHost.cs
  MediaBrowser.Api/Playback/BaseStreamingService.cs
  MediaBrowser.Api/Playback/Hls/DynamicHlsService.cs
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable-backport

#1903 Update NSIS Installer
  .ci/azure-pipelines.yml
  deployment/windows/build-jellyfin.ps1
  deployment/windows/dialogs/setuptype.nsddef
  deployment/windows/dialogs/setuptype.nsdinc
  deployment/windows/jellyfin.nsi
Labels: stable-backport

#1973 Fix the last of the docs warnings
  MediaBrowser.Api/PackageService.cs
  MediaBrowser.Model/Globalization/ILocalizationManager.cs
  MediaBrowser.Model/MediaBrowser.Model.csproj
  MediaBrowser.Model/Net/SocketReceiveResult.cs
  MediaBrowser.Providers/Tmdb/Models/Search/MovieResult.cs
Labels: documentation

#1929 [Draft][Help wanted] Fix parsing of certain names and adds a default season if no season was found
  Emby.Naming/Common/NamingOptions.cs
  Emby.Server.Implementations/Library/LibraryManager.cs
  MediaBrowser.sln
  tests/Jellyfin.Naming.Tests/EpisodePathParserTest.cs
  tests/Jellyfin.Naming.Tests/Jellyfin.Naming.Tests.csproj
Labels: stable-backport

#1864 Improve IInstallationManager interface
  Emby.Dlna/PlayTo/PlayToManager.cs
  Emby.Server.Implementations/ApplicationHost.cs
  Emby.Server.Implementations/ScheduledTasks/Tasks/PluginUpdateTask.cs
  Emby.Server.Implementations/Updates/InstallationManager.cs
  MediaBrowser.Api/PackageService.cs
  MediaBrowser.Api/Session/SessionsService.cs
  MediaBrowser.Common/IApplicationHost.cs
  MediaBrowser.Common/Updates/IInstallationManager.cs
  MediaBrowser.Model/Updates/PackageInfo.cs
  MediaBrowser.Providers/TV/TheTVDB/TvdbUtils.cs
  MediaBrowser.WebDashboard/Api/DashboardService.cs
Labels: Breaks Plugin API

#2008 Fix GetPathValue function
  Emby.Dlna/Api/DlnaServerService.cs
  Emby.Server.Implementations/HttpServer/HttpListenerHost.cs
  MediaBrowser.Api/ApiEntryPoint.cs
  MediaBrowser.Api/BaseApiService.cs
Labels: requires testing, stable-backport

#1992 Fix naming tests
  Emby.Naming/Common/NamingOptions.cs
  Emby.Naming/Emby.Naming.csproj
  tests/Jellyfin.Common.Tests/Jellyfin.Common.Tests.csproj
  tests/Jellyfin.Naming.Tests/EpisodePathParserTest.cs
  tests/Jellyfin.Naming.Tests/Jellyfin.Naming.Tests.csproj
Labels: stable-backport

#2019 Remove leading / from baseurl
  Emby.Dlna/Api/DlnaServerService.cs
  MediaBrowser.Api/BaseApiService.cs
Labels: stable-backport

#1925 Integrate web build into Debuntu package build steps
  deployment/debian-package-arm64/Dockerfile.amd64
  deployment/debian-package-arm64/Dockerfile.arm64
  deployment/debian-package-arm64/docker-build.sh
  deployment/debian-package-armhf/Dockerfile.amd64
  deployment/debian-package-armhf/Dockerfile.armhf
  deployment/debian-package-armhf/docker-build.sh
  deployment/debian-package-x64/Dockerfile
  deployment/debian-package-x64/docker-build.sh
  deployment/debian-package-x64/pkg-src/control
  deployment/debian-package-x64/pkg-src/rules
  deployment/ubuntu-package-arm64/Dockerfile.amd64
  deployment/ubuntu-package-arm64/Dockerfile.arm64
  deployment/ubuntu-package-arm64/docker-build.sh
  deployment/ubuntu-package-armhf/Dockerfile.amd64
  deployment/ubuntu-package-armhf/Dockerfile.armhf
  deployment/ubuntu-package-armhf/docker-build.sh
  deployment/ubuntu-package-x64/Dockerfile
  deployment/ubuntu-package-x64/docker-build.sh
Labels: build/platform

#2034 Fix easy password
  Emby.Server.Implementations/ApplicationHost.cs
  Emby.Server.Implementations/Library/UserManager.cs
Labels: requires testing, stable-backport

#2039 Fix always false condition
  MediaBrowser.Api/UserLibrary/PersonsService.cs
Labels: stable-backport

#2045 Fix baseurl issues part 2
  MediaBrowser.Api/BaseApiService.cs
Labels: stable-backport

#1991 Don't append transcodes to transcoding temp path
  Emby.Server.Implementations/AppBase/BaseConfigurationManager.cs
  Emby.Server.Implementations/ApplicationHost.cs
  Emby.Server.Implementations/Configuration/ServerConfigurationManager.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunUdpStream.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/LiveStream.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/M3UTunerHost.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/SharedHttpStream.cs
  Emby.Server.Implementations/ScheduledTasks/Tasks/DeleteTranscodeFileTask.cs
  Emby.Server.Implementations/ServerApplicationPaths.cs
  MediaBrowser.Api/ApiEntryPoint.cs
  MediaBrowser.Api/Playback/BaseStreamingService.cs
  MediaBrowser.Api/Playback/Hls/HlsSegmentService.cs
  MediaBrowser.Common/Configuration/EncodingConfigurationExtensions.cs
  MediaBrowser.Controller/IServerApplicationPaths.cs
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.MediaEncoding/Configuration/EncodingConfigurationFactory.cs
Labels: requires testing, stable-backport

#2054 dlna GetPathValue
  Emby.Dlna/Api/DlnaServerService.cs
Labels: stable-backport

#2058 Add full Raspberry Pi hardware accelerated decoding support
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
Labels: requires testing

#2071 add filesize limit for logfiles and a maximum logfile count
  Jellyfin.Server/Resources/Configuration/logging.json
Labels: stable-backport
