Repository jellyfin/jellyfin, pull requests merged in 2019-10, with the labels that each got.

#1825 Revert "Fix premature stop when streaming"
  MediaBrowser.Api/Playback/Hls/DynamicHlsService.cs
Labels: regression

#1862 Fix bump_version for submodule removal
  bump_version
Labels: stable-backport

#1866 Change slow query time logging to debug
  Emby.Server.Implementations/Data/SqliteItemRepository.cs
Labels: stable-backport

#1870 Fix exception when handling error, log errors better
  .gitattributes
  Emby.Server.Implementations/HttpServer/HttpListenerHost.cs
Labels: backend, stable-backport

#1863 Fix inconsistent BaseUrl behavior
  Emby.Server.Implementations/HttpServer/HttpListenerHost.cs
  MediaBrowser.Model/Configuration/ServerConfiguration.cs
Labels: stable-backport

#1861 Use NVM to install nodejs v8 and yarn for CentOS
  deployment/centos-package-x64/Dockerfile
  deployment/centos-package-x64/docker-build.sh
Labels: stable-backport

#1909 Fix System.NullReferenceException when playing Dvds copied to HDD
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable-backport

#1898 Fix Json serialization error
  Emby.Server.Implementations/Playlists/ManualPlaylistsFolder.cs
  Emby.Server.Implementations/Services/ServicePath.cs
  MediaBrowser.Common/MediaBrowser.Common.csproj
  MediaBrowser.Controller/Channels/Channel.cs
  MediaBrowser.Controller/Entities/AggregateFolder.cs
  MediaBrowser.Controller/Entities/Audio/Audio.cs
  MediaBrowser.Controller/Entities/Audio/MusicAlbum.cs
  MediaBrowser.Controller/Entities/Audio/MusicArtist.cs
  MediaBrowser.Controller/Entities/Audio/MusicGenre.cs
  MediaBrowser.Controller/Entities/AudioBook.cs
  MediaBrowser.Controller/Entities/BaseItem.cs
  MediaBrowser.Controller/Entities/BasePluginFolder.cs
  MediaBrowser.Controller/Entities/Book.cs
  MediaBrowser.Controller/Entities/CollectionFolder.cs
  MediaBrowser.Controller/Entities/Folder.cs
  MediaBrowser.Controller/Entities/Genre.cs
  MediaBrowser.Controller/Entities/ItemImageInfo.cs
  MediaBrowser.Controller/Entities/LinkedChild.cs
  MediaBrowser.Controller/Entities/Movies/BoxSet.cs
  MediaBrowser.Controller/Entities/Movies/Movie.cs
  MediaBrowser.Controller/Entities/MusicVideo.cs
  MediaBrowser.Controller/Entities/Person.cs
  MediaBrowser.Controller/Entities/Photo.cs
  MediaBrowser.Controller/Entities/PhotoAlbum.cs
  MediaBrowser.Controller/Entities/Studio.cs
  MediaBrowser.Controller/Entities/TV/Episode.cs
  MediaBrowser.Controller/Entities/TV/Season.cs
  MediaBrowser.Controller/Entities/TV/Series.cs
  MediaBrowser.Controller/Entities/Trailer.cs
  MediaBrowser.Controller/Entities/User.cs
  MediaBrowser.Controller/Entities/UserItemData.cs
  MediaBrowser.Controller/Entities/UserRootFolder.cs
  MediaBrowser.Controller/Entities/UserView.cs
  MediaBrowser.Controller/Entities/Video.cs
  MediaBrowser.Controller/Entities/Year.cs
  MediaBrowser.Controller/LiveTv/LiveTvChannel.cs
  MediaBrowser.Controller/LiveTv/LiveTvProgram.cs
  MediaBrowser.Controller/LiveTv/TimerInfo.cs
  MediaBrowser.Controller/Playlists/Playlist.cs
  MediaBrowser.Controller/Session/SessionInfo.cs
  MediaBrowser.Model/Dto/BaseItemPerson.cs
  MediaBrowser.Model/Dto/MediaSourceInfo.cs
  MediaBrowser.Model/MediaBrowser.Model.csproj
  MediaBrowser.Model/Serialization/IgnoreDataMemberAttribute.cs
  MediaBrowser.Model/Updates/PackageVersionInfo.cs
Labels: stable-backport

#1933 Reload logging.json on changes
  Jellyfin.Server/Program.cs
Labels: stable-backport

#1922 Use the correct dotnet runtime in Docker images
  Dockerfile
  Dockerfile.arm
  Dockerfile.arm64
Labels: requires testing

#1954 Use mirror for NSSM
  deployment/win-x64/docker-build.sh
  deployment/win-x86/docker-build.sh
  deployment/windows/build-jellyfin.ps1
Labels: stable-backport
