Repository jellyfin/jellyfin, pull requests merged in 2019-09, with the labels that each got.

#1692 NSIS improvements
  .ci/azure-pipelines.yml
  .gitignore
  deployment/windows/build-jellyfin.ps1
  deployment/windows/dependencies.txt
  deployment/windows/dialogs/confirmation.nsddef
  deployment/windows/dialogs/confirmation.nsdinc
  deployment/windows/dialogs/service-config.nsddef
  deployment/windows/dialogs/service-config.nsdinc
  deployment/windows/helpers/ShowError.nsh
  deployment/windows/helpers/StrSlash.nsh
  deployment/windows/jellyfin.nsi
  deployment/windows/legacy/install-jellyfin.ps1
  deployment/windows/legacy/install.bat
Labels: CI/project, build/platform

#1696 Add VSTest support to CI
  .ci/azure-pipelines.yml
Labels: CI/project

#1765 Add submodule update to CI build.
  .ci/azure-pipelines.yml
Labels: CI/project

#1770 Remove WAN IP Detection
  Emby.Server.Implementations/ApplicationHost.cs
  MediaBrowser.Model/System/PublicSystemInfo.cs
Labels: blocked
