Repository jellyfin/jellyfin, pull requests merged in 2020-04, with the labels that each got.

#2723 Update Jellyfin.SkiaSharp.NativeAssets.LinuxArm to version 1.68.1
  Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj
Labels: stable backport

#2730 Try to not crash on unsupported plugin load
  Emby.Server.Implementations/ApplicationHost.cs
Labels: stable backport

#2740 Fix GetLocalApiUrl for cases with https enabled
  Emby.Server.Implementations/ApplicationHost.cs
Labels: stable backport

#2758 Remove PluginInstalled
  Emby.Server.Implementations/ApplicationHost.cs
Labels: stable backport

#2796 Make codec check in profile examine profile type first
  MediaBrowser.Model/Dlna/DirectPlayProfile.cs
Labels: stable backport

#2721 Separate Channels permissions from All Libraries
  MediaBrowser.Api/UserLibrary/ItemsService.cs
Labels: stable backport

#2785 Fix MPEG4 packback error regression on vaapi
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#2821 Fix MPEG4 broken on VAAPI
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#2782 Fix support for attachments with baseURL set
  MediaBrowser.Api/Playback/MediaInfoService.cs
Labels: stable backport

#2779 Fix ffmpeg path on ARM docker image
  CONTRIBUTORS.md
  Dockerfile.arm
Labels: stable backport

#2783 Add logging of URL being processed when logging an error
  Emby.Server.Implementations/HttpServer/HttpListenerHost.cs
Labels: stable backport

#2715 Prefer to use libfdk_aac encoder for better audio quality when it is available
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
Labels: stable backport

#2745 Force Audio Transcoding for LiveTV Transcoding
  MediaBrowser.Api/Playback/MediaInfoService.cs
Labels: stable backport

#2848 Fix casing of JSON in Jellyfin API
  Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
Labels: stable backport

#2910 Additional mime types for DLNA (VLC)
  MediaBrowser.Model/Net/MimeTypes.cs
Labels: stable backport

#2864 Make Last-Modified and If-Modified-Since headers follow the spec
  Emby.Server.Implementations/HttpServer/HttpResultFactory.cs
Labels: stable backport

#2849 Handle null outputFileExtension in GetOutputFilePath
  MediaBrowser.Api/Playback/BaseStreamingService.cs
Labels: stable backport

#2928 Fix eTags DateLastSaved
  MediaBrowser.Controller/Entities/BaseItem.cs
Labels: stable backport

#2915 Fix imdbid regex
  Emby.Server.Implementations/Library/PathExtensions.cs
  MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs
Labels: stable backport

#2813 Switch to jellyfin-ffmpeg with integrated driver in docker build
  Dockerfile
Labels: stable backport

#2936 Remove JsonIgnore from the DateLastSaved property of BaseItem
  MediaBrowser.Controller/Entities/BaseItem.cs
Labels: stable backport

#2903 Fix DLNA clients displaying wrong album art.
  Emby.Dlna/Didl/DidlBuilder.cs
Labels: stable backport

#2620 Add Development Documentation To README
  .vscode/extensions.json
  README.md
Labels: enhancement

#2846 Remove requirement to build web during server builds
  .ci/azure-pipelines-compat.yml
  .ci/azure-pipelines-main.yml
  .ci/azure-pipelines-test.yml
  .ci/azure-pipelines.yml
  DvdLib/DvdLib.csproj
  Emby.Dlna/Emby.Dlna.csproj
  Emby.Drawing/Emby.Drawing.csproj
  Emby.Naming/Emby.Naming.csproj
  Emby.Notifications/Emby.Notifications.csproj
  Emby.Photos/Emby.Photos.csproj
  Emby.Server.Implementations/Emby.Server.Implementations.csproj
  Jellyfin.Api/Jellyfin.Api.csproj
  Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj
  Jellyfin.Server/Jellyfin.Server.csproj
  MediaBrowser.Api/MediaBrowser.Api.csproj
  MediaBrowser.Common/MediaBrowser.Common.csproj
  MediaBrowser.Controller/MediaBrowser.Controller.csproj
  MediaBrowser.LocalMetadata/MediaBrowser.LocalMetadata.csproj
  MediaBrowser.MediaEncoding/MediaBrowser.MediaEncoding.csproj
  MediaBrowser.Model/MediaBrowser.Model.csproj
  MediaBrowser.Providers/MediaBrowser.Providers.csproj
  MediaBrowser.WebDashboard/MediaBrowser.WebDashboard.csproj
  MediaBrowser.XbmcMetadata/MediaBrowser.XbmcMetadata.csproj
  RSSDP/RSSDP.csproj
  tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj
  tests/Jellyfin.Common.Tests/Jellyfin.Common.Tests.csproj
  tests/Jellyfin.Controller.Tests/Jellyfin.Controller.Tests.csproj
  tests/Jellyfin.MediaEncoding.Tests/Jellyfin.MediaEncoding.Tests.csproj
  tests/Jellyfin.Naming.Tests/Jellyfin.Naming.Tests.csproj
  tests/Jellyfin.Server.Implementations.Tests/Jellyfin.Server.Implementations.Tests.csproj
Labels: blocked

#2771 Enable nullabe reference types for Emby.Drawing and Jellyfin.Drawing.Skia
  Emby.Dlna/ConfigurationExtension.cs
  Emby.Drawing/Emby.Drawing.csproj
  Emby.Drawing/ImageProcessor.cs
  Emby.Server.Implementations/Data/SqliteItemRepository.cs
  Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj
  Jellyfin.Drawing.Skia/PlayedIndicatorDrawer.cs
  Jellyfin.Drawing.Skia/SkiaEncoder.cs
  Jellyfin.Drawing.Skia/StripCollageBuilder.cs
  Jellyfin.Drawing.Skia/UnplayedCountIndicator.cs
  MediaBrowser.Common/Extensions/ShuffleExtensions.cs
Labels: merge conflict

#2932 Add optional camelCase formatter
  Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
  Jellyfin.Server/Formatters/CamelCaseJsonProfileFormatter.cs
  Jellyfin.Server/Formatters/PascalCaseJsonProfileFormatter.cs
  Jellyfin.Server/Models/JsonOptions.cs
Labels: discussion needed

#2906 Fix InvalidOperationException while browsing via DLNA client.
  Emby.Dlna/Didl/DidlBuilder.cs
Labels: stable backport

#2798 Make localhost LiveTV restreams always use plain HTTP port
  Emby.Server.Implementations/ApplicationHost.cs
  Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunUdpStream.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/SharedHttpStream.cs
  Jellyfin.Server/Program.cs
  MediaBrowser.Controller/IServerApplicationHost.cs
Labels: stable backport

#2940 Fix missing colons
  Emby.Dlna/Profiles/DefaultProfile.cs
  Emby.Dlna/Profiles/Xml/Default.xml
  Emby.Dlna/Profiles/Xml/Denon AVR.xml
  Emby.Dlna/Profiles/Xml/DirecTV HD-DVR.xml
  Emby.Dlna/Profiles/Xml/LG Smart TV.xml
  Emby.Dlna/Profiles/Xml/Linksys DMA2100.xml
  Emby.Dlna/Profiles/Xml/Marantz.xml
  Emby.Dlna/Profiles/Xml/MediaMonkey.xml
  Emby.Dlna/Profiles/Xml/Panasonic Viera.xml
  Emby.Dlna/Profiles/Xml/Popcorn Hour.xml
  Emby.Dlna/Profiles/Xml/Samsung Smart TV.xml
  Emby.Dlna/Profiles/Xml/Sharp Smart TV.xml
  Emby.Dlna/Profiles/Xml/Sony Bravia (2011).xml
  Emby.Dlna/Profiles/Xml/Sony Bravia (2012).xml
  Emby.Dlna/Profiles/Xml/Sony Bravia (2013).xml
  Emby.Dlna/Profiles/Xml/Sony Bravia (2014).xml
  Emby.Dlna/Profiles/Xml/Sony PlayStation 3.xml
  Emby.Dlna/Profiles/Xml/Sony PlayStation 4.xml
  Emby.Dlna/Profiles/Xml/WDTV Live.xml
  Emby.Dlna/Profiles/Xml/Xbox One.xml
  Emby.Dlna/Profiles/Xml/foobar2000.xml
Labels: stable backport

#2990 Create Missing Data Folders
  Emby.Server.Implementations/Configuration/ServerConfigurationManager.cs
  Emby.Server.Implementations/ServerApplicationPaths.cs
  MediaBrowser.Common/Configuration/EncodingConfigurationExtensions.cs
  MediaBrowser.Controller/IServerApplicationPaths.cs
Labels: stable backport

#2995 Now parse date in header correctly as being in UTC
  Emby.Server.Implementations/HttpServer/HttpResultFactory.cs
Labels: stable backport

#2293 Add new EF Core data model (v2)
  Jellyfin.Data/DbContexts/Jellyfin.cs
  Jellyfin.Data/Entities/Artwork.cs
  Jellyfin.Data/Entities/Book.cs
  Jellyfin.Data/Entities/BookMetadata.cs
  Jellyfin.Data/Entities/Chapter.cs
  Jellyfin.Data/Entities/Collection.cs
  Jellyfin.Data/Entities/CollectionItem.cs
  Jellyfin.Data/Entities/Company.cs
  Jellyfin.Data/Entities/CompanyMetadata.cs
  Jellyfin.Data/Entities/CustomItem.cs
  Jellyfin.Data/Entities/CustomItemMetadata.cs
  Jellyfin.Data/Entities/Episode.cs
  Jellyfin.Data/Entities/EpisodeMetadata.cs
  Jellyfin.Data/Entities/Genre.cs
  Jellyfin.Data/Entities/Group.cs
  Jellyfin.Data/Entities/Library.cs
  Jellyfin.Data/Entities/LibraryItem.cs
  Jellyfin.Data/Entities/LibraryRoot.cs
  Jellyfin.Data/Entities/MediaFile.cs
  Jellyfin.Data/Entities/MediaFileStream.cs
  Jellyfin.Data/Entities/Metadata.cs
  Jellyfin.Data/Entities/MetadataProvider.cs
  Jellyfin.Data/Entities/MetadataProviderId.cs
  Jellyfin.Data/Entities/Movie.cs
  Jellyfin.Data/Entities/MovieMetadata.cs
  Jellyfin.Data/Entities/MusicAlbum.cs
  Jellyfin.Data/Entities/MusicAlbumMetadata.cs
  Jellyfin.Data/Entities/Permission.cs
  Jellyfin.Data/Entities/PermissionKind.cs
  Jellyfin.Data/Entities/Person.cs
  Jellyfin.Data/Entities/PersonRole.cs
  Jellyfin.Data/Entities/Photo.cs
  Jellyfin.Data/Entities/PhotoMetadata.cs
  Jellyfin.Data/Entities/Preference.cs
  Jellyfin.Data/Entities/PreferenceKind.cs
  Jellyfin.Data/Entities/ProviderMapping.cs
  Jellyfin.Data/Entities/Rating.cs
  Jellyfin.Data/Entities/RatingSource.cs
  Jellyfin.Data/Entities/Release.cs
  Jellyfin.Data/Entities/Season.cs
  Jellyfin.Data/Entities/SeasonMetadata.cs
  Jellyfin.Data/Entities/Series.cs
  Jellyfin.Data/Entities/SeriesMetadata.cs
  Jellyfin.Data/Entities/Track.cs
  Jellyfin.Data/Entities/TrackMetadata.cs
  Jellyfin.Data/Entities/User.cs
  Jellyfin.Data/Enums/ArtKind.cs
  Jellyfin.Data/Enums/MediaFileKind.cs
  Jellyfin.Data/Enums/PersonRoleType.cs
  Jellyfin.Data/Enums/Weekday.cs
  Jellyfin.Data/Jellyfin.Data.csproj
  Jellyfin.Data/Structs/.gitkeep
  MediaBrowser.sln
Labels: help wanted, roadmap
