Repository jellyfin/jellyfin, pull requests merged in 2020-06, with the labels that each got.

#2676 Implement Blurhash generation for images
  .vscode/tasks.json
  Emby.Drawing/ImageProcessor.cs
  Emby.Drawing/NullImageEncoder.cs
  Emby.Server.Implementations/Data/SqliteItemRepository.cs
  Emby.Server.Implementations/Dto/DtoService.cs
  Emby.Server.Implementations/Library/LibraryManager.cs
  Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj
  Jellyfin.Drawing.Skia/SkiaEncoder.cs
  MediaBrowser.Api/Images/ImageService.cs
  MediaBrowser.Controller/Drawing/IImageEncoder.cs
  MediaBrowser.Controller/Drawing/IImageProcessor.cs
  MediaBrowser.Controller/Entities/BaseItem.cs
  MediaBrowser.Controller/Entities/Folder.cs
  MediaBrowser.Controller/Entities/ItemImageInfo.cs
  MediaBrowser.Controller/Library/ILibraryManager.cs
  MediaBrowser.Model/Dto/BaseItemDto.cs
  MediaBrowser.Model/Dto/ImageInfo.cs
Labels: needs testing

#2154 Add image provider for artists
  Emby.Server.Implementations/Images/ArtistImageProvider.cs
  Emby.Server.Implementations/Images/BaseDynamicImageProvider.cs
  Emby.Server.Implementations/Images/CollectionFolderImageProvider.cs
  Emby.Server.Implementations/Images/DynamicImageProvider.cs
  Emby.Server.Implementations/Images/FolderImageProvider.cs
  Emby.Server.Implementations/Images/GenreImageProvider.cs
  Emby.Server.Implementations/Images/PlaylistImageProvider.cs
  Jellyfin.Drawing.Skia/SkiaEncoder.cs
Labels: discussion needed

#3137 Correctly Support Translating External Ids
  MediaBrowser.Controller/Providers/IExternalId.cs
  MediaBrowser.LocalMetadata/Parsers/BaseItemXmlParser.cs
  MediaBrowser.Model/Providers/ExternalIdInfo.cs
  MediaBrowser.Model/Providers/ExternalIdMediaType.cs
  MediaBrowser.Providers/Manager/ProviderManager.cs
  MediaBrowser.Providers/Movies/MovieExternalIds.cs
  MediaBrowser.Providers/Music/MusicExternalIds.cs
  MediaBrowser.Providers/Plugins/AudioDb/ExternalIds.cs
  MediaBrowser.Providers/Plugins/MusicBrainz/ExternalIds.cs
  MediaBrowser.Providers/Plugins/Tmdb/BoxSets/TmdbBoxSetExternalId.cs
  MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieExternalId.cs
  MediaBrowser.Providers/Plugins/Tmdb/People/TmdbPersonExternalId.cs
  MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeriesExternalId.cs
  MediaBrowser.Providers/TV/TvExternalIds.cs
Labels: breaking change: plugin api

#3378 [SyncPlay] Remove (unused) SessionId route parameter
  MediaBrowser.Api/SyncPlay/SyncPlayService.cs
Labels: breaking change: web api

#3451 Move StudiosService.cs to Jellyfin.Api
  Jellyfin.Api/Controllers/StudiosController.cs
  Jellyfin.Api/Helpers/RequestHelpers.cs
  MediaBrowser.Api/UserLibrary/StudiosService.cs
Labels: merge conflict

#3478 bump autofixture
  tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj
  tests/Jellyfin.Server.Implementations.Tests/Jellyfin.Server.Implementations.Tests.csproj
Labels: dependencies
