Repository jellyfin/jellyfin, pull requests merged in 2020-12, with the labels that each got.

#4665 Fix the NPM publish scope to public
  .ci/azure-pipelines-api-client.yml
Labels: stable backport

#4662 Fix bad do in bump_version
  bump_version
Labels: stable backport

#4669 Fix NPM command in CI
  .ci/azure-pipelines-api-client.yml
Labels: stable backport

#4667 Remove obsolete erroring command
  .ci/azure-pipelines-package.yml
Labels: stable backport

#4672 Fix MergeVersions endpoint
  Jellyfin.Api/Controllers/VideosController.cs
Labels: stable backport

#4671 Clear KnownNetworks and KnownProxies if none are configured explicitly
  Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
Labels: stable backport

#4711 Add required attributes to parameters
  Jellyfin.Api/Controllers/UserController.cs
Labels: stable backport

#4678 Change logging level and message in NetworkManager
  Jellyfin.Networking/Manager/NetworkManager.cs
Labels: stable backport

#4706 Only apply series image aspect ratio if episode/season has no primary image
  Emby.Server.Implementations/Dto/DtoService.cs
Labels: stable backport

#4715 Add number to bool json converter
  Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs
  MediaBrowser.Common/Json/Converters/JsonBoolNumberConverter.cs
  MediaBrowser.Common/Json/JsonDefaults.cs
  tests/Jellyfin.Common.Tests/Json/JsonBoolNumberTests.cs
Labels: stable backport

#4722 Fix API forbidden response
  Jellyfin.Api/Controllers/ImageController.cs
  Jellyfin.Api/Controllers/QuickConnectController.cs
  Jellyfin.Api/Controllers/UserController.cs
Labels: stable backport

#4735 Fix JsonConverter recursion
  Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs
  MediaBrowser.Common/Json/Converters/JsonBoolNumberConverter.cs
  tests/Jellyfin.Common.Tests/Json/JsonBoolNumberTests.cs
Labels: stable backport

#4730 Don't serialize empty GUID to null
  Emby.Server.Implementations/LiveTv/LiveTvManager.cs
  MediaBrowser.Common/Json/Converters/JsonGuidConverter.cs
  MediaBrowser.Model/Dto/BaseItemDto.cs
  tests/Jellyfin.Common.Tests/Json/JsonGuidConverterTests.cs
Labels: stable backport

#4736 Fix custom library order
  Emby.Server.Implementations/Library/UserViewManager.cs
Labels: stable backport

#4733 Fix potential null reference in OMDB
  MediaBrowser.Providers/Plugins/Omdb/OmdbProvider.cs
Labels: stable backport

#4741 Add tests for HdHomerunHost.GetLineup
  Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/Channels.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/DiscoverResponse.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs
  tests/Jellyfin.Server.Implementations.Tests/Jellyfin.Server.Implementations.Tests.csproj
  tests/Jellyfin.Server.Implementations.Tests/LiveTv/HdHomerunHostTests.cs
  tests/Jellyfin.Server.Implementations.Tests/LiveTv/lineup.json
Labels: stable backport

#4743 Actually use library options when filtering metadata providers
  MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs
Labels: stable backport

#4751 Use larger batch size on mpegts to avoid corrupted thumbnails
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Labels: stable backport

#4701 Don't return plugin versions that target newer Jellyfin version
  Emby.Server.Implementations/Updates/InstallationManager.cs
Labels: stable backport

#4753 Update to dotnet 5.0.1
  Emby.Server.Implementations/Emby.Server.Implementations.csproj
  Jellyfin.Api/Jellyfin.Api.csproj
  Jellyfin.Data/Jellyfin.Data.csproj
  Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj
  Jellyfin.Server/Jellyfin.Server.csproj
  deployment/Dockerfile.debian.amd64
  deployment/Dockerfile.debian.arm64
  deployment/Dockerfile.debian.armhf
  deployment/Dockerfile.linux.amd64
  deployment/Dockerfile.macos
  deployment/Dockerfile.portable
  deployment/Dockerfile.ubuntu.amd64
  deployment/Dockerfile.ubuntu.arm64
  deployment/Dockerfile.ubuntu.armhf
  deployment/Dockerfile.windows.amd64
  tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj
Labels: stable backport

#4749 Serialize GUID without dashes
  MediaBrowser.Common/Json/Converters/JsonGuidConverter.cs
  tests/Jellyfin.Common.Tests/Json/JsonGuidConverterTests.cs
Labels: stable backport

#4762 Fix openapi file schema
  Jellyfin.Server/Filters/FileResponseFilter.cs
Labels: stable backport

#4757 Remove ImageFetcherPostScanTask
  Emby.Server.Implementations/Library/ImageFetcherPostScanTask.cs
  Emby.Server.Implementations/Library/LibraryManager.cs
  MediaBrowser.Controller/Entities/BaseItem.cs
  MediaBrowser.Controller/Entities/Folder.cs
  MediaBrowser.Controller/Library/ILibraryManager.cs
  MediaBrowser.Providers/Manager/MetadataService.cs
Labels: stable backport

#4737 Add missing EnsureSuccessStatusCode
  Emby.Server.Implementations/LiveTv/Listings/SchedulesDirect.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs
  Emby.Server.Implementations/Updates/InstallationManager.cs
Labels: stable backport

#4756 Fix inverted condition when authenticating with an ApiKey
  Emby.Server.Implementations/HttpServer/Security/AuthorizationContext.cs
Labels: stable backport

#4724 Fix null reference error in Dlna PlayTo
  Emby.Dlna/PlayTo/PlayToController.cs
Labels: stable backport

#4710 Restore sessions in SyncPlay groups upon reconnection
  Emby.Server.Implementations/Session/SessionManager.cs
  Emby.Server.Implementations/Session/SessionWebSocketListener.cs
  Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs
  MediaBrowser.Controller/Session/ISessionManager.cs
Labels: stable backport

#4699 Fix CustomItemDisplayPreferences unique key collision in the migration
  Jellyfin.Server/Migrations/Routines/MigrateDisplayPreferencesDb.cs
Labels: stable backport

#4774 Fine tune some tone mapping params
  MediaBrowser.Model/Configuration/EncodingOptions.cs
Labels: stable backport

#4767 Fix SSL certificate cannot be saved
  Emby.Server.Implementations/ApplicationHost.cs
  Emby.Server.Implementations/Configuration/ServerConfigurationManager.cs
  Jellyfin.Networking/Configuration/NetworkConfiguration.cs
Labels: stable backport

#4758 Fix landing screen options
  Jellyfin.Api/Controllers/DisplayPreferencesController.cs
  Jellyfin.Data/Entities/ItemDisplayPreferences.cs
  Jellyfin.Data/Enums/ViewType.cs
Labels: stable backport

#4761 Convert CreatePlaylist to use query params instead of body
  Jellyfin.Api/Controllers/MediaInfoController.cs
  Jellyfin.Api/Controllers/PlaylistsController.cs
  Jellyfin.Api/Models/PlaylistDtos/CreatePlaylistDto.cs
Labels: stable backport

#4726 Fix - Access Denied on using certificates in windows as user.
  Emby.Server.Implementations/ApplicationHost.cs
Labels: stable backport

#4769 Check correct fetcher list for provider name
  MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs
Labels: stable backport

#4675 Ability to use DNS names in KnownProxies
  Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
Labels: stable backport

#4713 Redirect robots.txt if hosting web content
  Jellyfin.Server/Extensions/ApiApplicationBuilderExtensions.cs
  Jellyfin.Server/Middleware/LegacyEmbyRouteRewriteMiddleware.cs
  Jellyfin.Server/Middleware/RobotsRedirectionMiddleware.cs
  Jellyfin.Server/Startup.cs
Labels: stable backport

#4750 Fix blueberry
  Jellyfin.Drawing.Skia/SkiaEncoder.cs
Labels: stable backport

#4773 Remove opf extension for book types
  Emby.Server.Implementations/Library/Resolvers/Books/BookResolver.cs
Labels: regression, stable backport

#4716 Update authorization policies for SyncPlay
  Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs
  Jellyfin.Api/Auth/SyncPlayAccessPolicy/SyncPlayAccessHandler.cs
  Jellyfin.Api/Auth/SyncPlayAccessPolicy/SyncPlayAccessRequirement.cs
  Jellyfin.Api/Constants/Policies.cs
  Jellyfin.Api/Controllers/SyncPlayController.cs
  Jellyfin.Data/Entities/User.cs
  Jellyfin.Data/Enums/SyncPlayAccessRequirementType.cs
  Jellyfin.Data/Enums/SyncPlayUserAccessType.cs
  Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
  MediaBrowser.Controller/SyncPlay/ISyncPlayManager.cs
  MediaBrowser.Model/Users/UserPolicy.cs
Labels: stable backport

#4789 Fix get provider id extension
  MediaBrowser.Model/Entities/ProviderIdsExtensions.cs
Labels: stable backport

#4781 Use request body for mapping xml channels
  Jellyfin.Api/Controllers/LiveTvController.cs
  Jellyfin.Api/Models/LiveTvDtos/SetChannelMappingDto.cs
Labels: stable backport

#4794 Convert from base64 when saving item images
  Jellyfin.Api/Controllers/ImageController.cs
Labels: stable backport

#4792 Add missing seasons during AfterMetadataRefresh
  MediaBrowser.Providers/TV/SeriesMetadataService.cs
Labels: stable backport

#4807 Correct DLNA audio codecs for PS3 and PS4
  Emby.Dlna/Profiles/SonyPs3Profile.cs
  Emby.Dlna/Profiles/SonyPs4Profile.cs
  Emby.Dlna/Profiles/Xml/Sony PlayStation 3.xml
  Emby.Dlna/Profiles/Xml/Sony PlayStation 4.xml
Labels: stable backport

#4771 Use typed UserManager GetPreference
  Emby.Server.Implementations/Library/UserViewManager.cs
  Emby.Server.Implementations/TV/TVSeriesManager.cs
  Jellyfin.Api/Controllers/ItemsController.cs
  Jellyfin.Data/Entities/User.cs
  Jellyfin.Server.Implementations/Users/UserManager.cs
  Jellyfin.Server/Migrations/Routines/MigrateUserDb.cs
  MediaBrowser.Controller/Channels/Channel.cs
  MediaBrowser.Controller/Entities/Audio/MusicAlbum.cs
  MediaBrowser.Controller/Entities/Audio/MusicArtist.cs
  MediaBrowser.Controller/Entities/BaseItem.cs
  MediaBrowser.Controller/Entities/Folder.cs
  MediaBrowser.Controller/Entities/Movies/BoxSet.cs
  MediaBrowser.Controller/Entities/TV/Series.cs
Labels: stable backport

#4819 Set filename when downloading file
  Jellyfin.Api/Controllers/LibraryController.cs
Labels: stable backport

#4828 Add static Linux builds for arm and musl
  .ci/azure-pipelines-package.yml
  deployment/Dockerfile.linux.amd64-musl
  deployment/Dockerfile.linux.arm64
  deployment/Dockerfile.linux.armhf
  deployment/build.linux.amd64-musl
  deployment/build.linux.arm64
  deployment/build.linux.armhf
Labels: stable backport

#4803 Fix Live TV Recording Scheduling
  Emby.Server.Implementations/HttpServer/Security/SessionContext.cs
Labels: stable backport

#4816 Fix some video profiles for Android client
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#4833 Fix similar items endpoint for movies and TV
  Jellyfin.Api/Controllers/LibraryController.cs
Labels: stable backport

#4836 Return dashboardTheme when requesting DisplayPreferences
  Jellyfin.Api/Controllers/DisplayPreferencesController.cs
Labels: stable backport

#4824 Add request parameters to OpenLiveStreamDto
  Jellyfin.Api/Controllers/MediaInfoController.cs
  Jellyfin.Api/Models/MediaInfoDtos/OpenLiveStreamDto.cs
Labels: stable backport

#4842 Add JsonDateTimeConverter
  MediaBrowser.Common/Json/Converters/JsonDateTimeConverter.cs
  MediaBrowser.Common/Json/JsonDefaults.cs
Labels: stable backport

#4821 Fix: Disable dlna server API responses if dlna is disabled.
  Emby.Dlna/Main/DlnaEntryPoint.cs
  Jellyfin.Api/Controllers/DlnaServerController.cs
Labels: stable backport

#4847 Fix another key collision in MigrateDisplayPreferencesDatabase
  Jellyfin.Server/Migrations/Routines/MigrateDisplayPreferencesDb.cs
Labels: stable backport

#4850 Null reference fix
  Jellyfin.Api/Controllers/SystemController.cs
Labels: stable backport

#4852 SchedulesDirect no longer refreshes channels properly
  Emby.Server.Implementations/LiveTv/Listings/SchedulesDirect.cs
Labels: stable backport

#4855 Initialize JsonSerializerOptions statically
  MediaBrowser.Common/Json/JsonDefaults.cs
Labels: stable backport

#4856 Fix some profiles for H264 AMF encoder
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#4861 Fix null reference when logging
  MediaBrowser.Model/Dlna/StreamBuilder.cs
Labels: stable backport

#4863 Fix boxes in library name backdrop
  Jellyfin.Drawing.Skia/StripCollageBuilder.cs
Labels: stable backport

#4860 Avoid transcoding to 3ch audio for HLS streaming
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#4874 Enable TMDB and OMDB by default
  MediaBrowser.Model/Configuration/ServerConfiguration.cs
Labels: stable backport

#4872 Removed workaround code as web is now fixed.
  Jellyfin.Networking/Manager/NetworkManager.cs
Labels: stable backport

#4891 Split resume function for Audiobooks
  Emby.Server.Implementations/Library/UserDataManager.cs
  MediaBrowser.Model/Configuration/ServerConfiguration.cs
Labels: stable backport

#4890 Fix search hint endpoint error
  Emby.Server.Implementations/Library/SearchEngine.cs
Labels: stable backport

#4884 Add JsonConverter for Nullable Guids
  MediaBrowser.Common/Json/Converters/JsonNullableGuidConverter.cs
  MediaBrowser.Common/Json/JsonDefaults.cs
  tests/Jellyfin.Common.Tests/Json/JsonNullableGuidConverterTests.cs
Labels: stable backport

#4729 Disable DLNA when HTTPS is required
  Emby.Dlna/Main/DlnaEntryPoint.cs
  Jellyfin.Networking/Manager/NetworkManager.cs
Labels: stable backport

#4902 Fixed loopback subnet
  MediaBrowser.Common/Net/IPNetAddress.cs
Labels: stable backport

#4709 Improved plugin management functionality
  Emby.Server.Implementations/ApplicationHost.cs
  Emby.Server.Implementations/Emby.Server.Implementations.csproj
  Emby.Server.Implementations/Plugins/PluginManager.cs
  Emby.Server.Implementations/Plugins/PluginManifest.cs
  Emby.Server.Implementations/ScheduledTasks/Tasks/PluginUpdateTask.cs
  Emby.Server.Implementations/Updates/InstallationManager.cs
  Jellyfin.Api/Controllers/DashboardController.cs
  Jellyfin.Api/Controllers/PackageController.cs
  Jellyfin.Api/Controllers/PluginsController.cs
  Jellyfin.Api/Models/ConfigurationPageInfo.cs
  Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
  MediaBrowser.Common/IApplicationHost.cs
  MediaBrowser.Common/Json/JsonDefaults.cs
  MediaBrowser.Common/Plugins/BasePlugin.cs
  MediaBrowser.Common/Plugins/BasePluginOfT.cs
  MediaBrowser.Common/Plugins/IHasPluginConfiguration.cs
  MediaBrowser.Common/Plugins/IPlugin.cs
  MediaBrowser.Common/Plugins/IPluginManager.cs
  MediaBrowser.Common/Plugins/LocalPlugin.cs
  MediaBrowser.Common/Plugins/PluginManifest.cs
  MediaBrowser.Common/Updates/IInstallationManager.cs
  MediaBrowser.Common/Updates/InstallationEventArgs.cs
  MediaBrowser.Controller/Events/Updates/PluginUninstalledEventArgs.cs
  MediaBrowser.Controller/IServerApplicationHost.cs
  MediaBrowser.Model/Configuration/ServerConfiguration.cs
  MediaBrowser.Model/Plugins/PluginInfo.cs
  MediaBrowser.Model/Plugins/PluginPageInfo.cs
  MediaBrowser.Model/Plugins/PluginStatus.cs
  MediaBrowser.Model/Updates/InstallationInfo.cs
  MediaBrowser.Model/Updates/PackageInfo.cs
  MediaBrowser.Model/Updates/VersionInfo.cs
  MediaBrowser.Providers/Plugins/AudioDb/Plugin.cs
  MediaBrowser.Providers/Plugins/MusicBrainz/Plugin.cs
  MediaBrowser.Providers/Plugins/Omdb/Plugin.cs
  MediaBrowser.sln
Labels: release critical, stable backport
