Repository jellyfin/jellyfin, pull requests merged in 2020-11, with the labels that each got.

#3196 Remove "download images in advance" option
  Jellyfin.Server/Migrations/MigrationRunner.cs
  Jellyfin.Server/Migrations/Routines/RemoveDownloadImagesInAdvance.cs
  MediaBrowser.Model/Configuration/LibraryOptions.cs
  MediaBrowser.Providers/Manager/ItemImageProvider.cs
  MediaBrowser.Providers/Manager/MetadataService.cs
Labels: breaking change: web api

#4500 Use .NET 5.0 in Nuget pipeline
  .ci/azure-pipelines-package.yml
Labels: .NET5, build

#4263 Defer image pre-fetching until the end of a refresh/scan
  Emby.Server.Implementations/Library/ImageFetcherPostScanTask.cs
  Emby.Server.Implementations/Library/LibraryManager.cs
  MediaBrowser.Controller/Entities/BaseItem.cs
  MediaBrowser.Controller/Entities/Folder.cs
  MediaBrowser.Controller/Library/ILibraryManager.cs
  MediaBrowser.Providers/Manager/MetadataService.cs
Labels: hacktoberfest-accepted
