Repository jellyfin/jellyfin, pull requests merged in 2021-12, with the labels that each got.

#6819 Try to use Width and Height from ImageInfo to determine aspect ratio
  Emby.Server.Implementations/Dto/DtoService.cs
Labels: needs testing

#5009 Move studios image providers to plugin
  MediaBrowser.Providers/MediaBrowser.Providers.csproj
  MediaBrowser.Providers/Plugins/StudioImages/Configuration/PluginConfiguration.cs
  MediaBrowser.Providers/Plugins/StudioImages/Configuration/config.html
  MediaBrowser.Providers/Plugins/StudioImages/Plugin.cs
  MediaBrowser.Providers/Plugins/StudioImages/StudiosImageProvider.cs
Labels: enhancement

#7070 Fix Fedora build version
  fedora/Makefile
Labels: build, ci
