Repository jellyfin/jellyfin, pull requests merged in 2021-09, with the labels that each got.

#6512 Preferences fix
  Dockerfile
  Jellyfin.Data/Entities/CustomItemDisplayPreferences.cs
Labels: stable backport

#6569 Update to dotnet 5.0.10
  Emby.Server.Implementations/Emby.Server.Implementations.csproj
  Jellyfin.Api/Jellyfin.Api.csproj
  Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj
  Jellyfin.Server/Jellyfin.Server.csproj
  deployment/Dockerfile.ubuntu.amd64
  deployment/Dockerfile.ubuntu.arm64
  deployment/Dockerfile.ubuntu.armhf
  tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj
  tests/Jellyfin.Server.Integration.Tests/Jellyfin.Server.Integration.Tests.csproj
  tests/Jellyfin.Server.Tests/Jellyfin.Server.Tests.csproj
Labels: dependencies, .NET

#6594 ci - target net6.0
  .ci/azure-pipelines-abi.yml
  .ci/azure-pipelines-main.yml
  .ci/azure-pipelines-package.yml
  .ci/azure-pipelines-test.yml
  .ci/azure-pipelines.yml
Labels: ci
