Repository jellyfin/jellyfin, pull requests merged in 2021-03, with the labels that each got.

#5342 Corrected logging message
  Jellyfin.Server/Program.cs
Labels: stable backport

#5339 Revert breaking change to HasProviderId
  MediaBrowser.Model/Entities/ProviderIdsExtensions.cs
  tests/Jellyfin.Model.Tests/Entities/ProviderIdsExtensionsTests.cs
Labels: stable backport

#5349 Fix TMDb search name containing year
  MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbEpisodeProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeriesProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/TmdbClientManager.cs
Labels: stable backport

#5335 Remove Content-Length header from DLNA HEAD request
  Emby.Dlna/PlayTo/PlayToController.cs
  Jellyfin.Api/Helpers/FileStreamResponseHelpers.cs
Labels: stable backport

#5356 return false when providerid is null or empty
  MediaBrowser.Model/Entities/ProviderIdsExtensions.cs
  MediaBrowser.Providers/Manager/ProviderManager.cs
  tests/Jellyfin.Model.Tests/Entities/ProviderIdsExtensionsTests.cs
Labels: stable backport

#5345 Dual IP4 / IP6 server fails on non-windows platforms
  Jellyfin.Networking/Manager/NetworkManager.cs
  Jellyfin.Server/Program.cs
Labels: stable backport

#5375 Specify defaults or set query parameter to nullable
  Jellyfin.Api/Controllers/AudioController.cs
  Jellyfin.Api/Controllers/DynamicHlsController.cs
  Jellyfin.Api/Controllers/HlsSegmentController.cs
  Jellyfin.Api/Controllers/ImageController.cs
  Jellyfin.Api/Controllers/ItemUpdateController.cs
  Jellyfin.Api/Controllers/LibraryController.cs
  Jellyfin.Api/Controllers/PlaystateController.cs
  Jellyfin.Api/Controllers/UniversalAudioController.cs
  Jellyfin.Api/Controllers/VideoHlsController.cs
  Jellyfin.Api/Controllers/VideosController.cs
Labels: stable backport

#5378 Fix UpdateMediaPath model binding
  Jellyfin.Api/Controllers/LibraryStructureController.cs
  Jellyfin.Api/Models/LibraryStructureDto/UpdateMediaPathRequestDto.cs
Labels: stable backport

#5377 Do not use language or imagelanguages when searching for images with TMDb
  MediaBrowser.Providers/Manager/ProviderManager.cs
  MediaBrowser.Providers/Plugins/Tmdb/BoxSets/TmdbBoxSetImageProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieImageProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbEpisodeImageProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeasonImageProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeriesImageProvider.cs
Labels: stable backport

#5383 do not pick a linked item as primary when merging versions
  Jellyfin.Api/Controllers/VideosController.cs
Labels: stable backport

#5381 make sure network path substitution matches correctly
  Emby.Server.Implementations/Library/LibraryManager.cs
  Emby.Server.Implementations/Library/PathExtensions.cs
  tests/Jellyfin.Server.Implementations.Tests/Library/PathExtensionsTests.cs
Labels: stable backport

#5402 Use FileShare.None when creating files
  Emby.Dlna/DlnaManager.cs
  Emby.Server.Implementations/AppBase/ConfigurationHelper.cs
  Emby.Server.Implementations/LiveTv/EmbyTV/DirectRecorder.cs
  Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs
  Emby.Server.Implementations/LiveTv/EmbyTV/EncodedRecorder.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunUdpStream.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/SharedHttpStream.cs
  Jellyfin.Api/Controllers/ItemLookupController.cs
  Jellyfin.Api/Controllers/RemoteImageController.cs
  Jellyfin.Api/Helpers/TranscodingJobHelper.cs
  MediaBrowser.LocalMetadata/Savers/BaseXmlSaver.cs
  MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
  MediaBrowser.Providers/Manager/ImageSaver.cs
  MediaBrowser.Providers/Plugins/AudioDb/AlbumProvider.cs
  MediaBrowser.Providers/Plugins/AudioDb/ArtistProvider.cs
  MediaBrowser.Providers/Subtitles/SubtitleManager.cs
Labels: stable backport

#5407 Fix casing CollectionType
  Emby.Server.Implementations/Library/LibraryManager.cs
  MediaBrowser.Model/Entities/JsonLowerCaseConverter.cs
  MediaBrowser.Model/Entities/VirtualFolderInfo.cs
  tests/Jellyfin.Model.Tests/Entities/JsonLowerCaseConverterTests.cs
Labels: stable backport

#5409 Changed string.Length == 0 to string.IsNullOrEmpty in case of null
  CONTRIBUTORS.md
  Emby.Server.Implementations/Library/PathExtensions.cs
Labels: stable backport

#5406 do not throw ArgumentNullException in TryCleanString
  Emby.Naming/Video/CleanStringParser.cs
  tests/Jellyfin.Naming.Tests/Video/CleanStringTests.cs
Labels: stable backport

#5315 Fix for environment variable JELLYFIN_PublishedServerUrl being ignored.
  Emby.Dlna/Main/DlnaEntryPoint.cs
  Emby.Server.Implementations/ApplicationHost.cs
  Emby.Server.Implementations/IStartupOptions.cs
  Jellyfin.Server/CoreAppHost.cs
  Jellyfin.Server/Program.cs
  Jellyfin.Server/StartupOptions.cs
  MediaBrowser.Controller/IServerApplicationHost.cs
  tests/Jellyfin.Api.Tests/JellyfinApplicationFactory.cs
  tests/Jellyfin.Api.Tests/TestAppHost.cs
Labels: stable backport

#5444 Use FileShare.Read to fix HdHomeRun
  Emby.Server.Implementations/LiveTv/EmbyTV/EncodedRecorder.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunUdpStream.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/SharedHttpStream.cs
  Jellyfin.Api/Helpers/TranscodingJobHelper.cs
Labels: regression, stable backport

#5447 Remove Microsoft repo from install step
  deployment/Dockerfile.fedora.amd64
Labels: stable backport

#5431 Use imdbid as fallback in movie provider
  MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeriesProvider.cs
Labels: stable backport

#5403 Various DLNA Device Profile fixes
  Emby.Dlna/Profiles/DefaultProfile.cs
  Jellyfin.Api/Helpers/StreamingHelpers.cs
Labels: stable backport

#5461 fix multiversion eligibility check for complex folder names
  Emby.Naming/Video/VideoListResolver.cs
  tests/Jellyfin.Naming.Tests/Video/MultiVersionTests.cs
Labels: stable backport

#5480 Add SessionMessageType to generated openapi spec
  Jellyfin.Server/Filters/WebsocketModelFilter.cs
Labels: stable backport

#5457 Use distinct for AllArtists to avoid double refreshing
  MediaBrowser.Controller/Entities/Audio/IHasAlbumArtist.cs
  MediaBrowser.Controller/Library/NameExtensions.cs
Labels: stable backport

#5500 Fix third party integration
  Jellyfin.Api/Controllers/LibraryController.cs
  Jellyfin.Api/Controllers/NotificationsController.cs
  Jellyfin.Api/Models/LibraryDtos/MediaUpdateInfoDto.cs
  Jellyfin.Api/Models/LibraryDtos/MediaUpdateInfoPathDto.cs
  Jellyfin.Api/Models/NotificationDtos/AdminNotificationDto.cs
Labels: stable backport

#5515 fix refresh endpoint
  Jellyfin.Api/Controllers/LibraryController.cs
Labels: stable backport

#5518 Add missing InstantMix endpoints
  Jellyfin.Api/Controllers/InstantMixController.cs
Labels: stable backport

#5324 Fix duplicated movies when group movies into collections is enabled
  Emby.Server.Implementations/Collections/CollectionManager.cs
Labels: stable backport

#5510 Fix: Streaming crashing due to no deviceProfileId match.
  Emby.Dlna/DlnaManager.cs
Labels: stable backport

#5475 Null pointer fix in DLNA when its disabled.
  Emby.Dlna/Main/DlnaEntryPoint.cs
  Emby.Dlna/Ssdp/DeviceDiscovery.cs
Labels: stable backport

#5512 Set openapi version to server version
  Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
Labels: stable backport

#5550 revert underscore as a multiversion separator
  Emby.Naming/Video/VideoListResolver.cs
  tests/Jellyfin.Naming.Tests/Video/MultiVersionTests.cs
Labels: stable backport

#5559 Clean the entity name for non-words before searching
  MediaBrowser.Providers/Plugins/Tmdb/BoxSets/TmdbBoxSetProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeriesProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/TmdbUtils.cs
Labels: stable backport

#5504 Add JsonStringConverter
  MediaBrowser.Common/Json/Converters/JsonStringConverter.cs
  MediaBrowser.Common/Json/JsonDefaults.cs
  tests/Jellyfin.Common.Tests/Json/JsonStringConverterTests.cs
Labels: stable backport

#5476 Remove BuildPackage dependency for PublishNuget in CI
  .ci/azure-pipelines-package.yml
Labels: build, stable backport

#5532 do not resolve episode-like files if they are in extras folders
  Emby.Server.Implementations/Library/Resolvers/BaseVideoResolver.cs
  Emby.Server.Implementations/Library/Resolvers/Books/BookResolver.cs
  Emby.Server.Implementations/Library/Resolvers/Movies/MovieResolver.cs
  Emby.Server.Implementations/Library/Resolvers/TV/EpisodeResolver.cs
  MediaBrowser.Controller/Resolvers/BaseItemResolver.cs
  tests/Jellyfin.Server.Implementations.Tests/Library/EpisodeResolverTest.cs
Labels: stable backport

#5613 Improve responses to HEAD /audio/<id>/stream for Samsung DLNA renderers
  Jellyfin.Api/Helpers/FileStreamResponseHelpers.cs
Labels: stable backport

#5596 Implemented DLNA exception handling
  Emby.Dlna/PlayTo/Device.cs
  Emby.Dlna/PlayTo/PlayToManager.cs
  Emby.Dlna/PlayTo/SsdpHttpClient.cs
  tests/Jellyfin.Networking.Tests/NetworkParseTests.cs
Labels: stable backport

#5620 Ignore ffmpeg input format for ISO files and fix input path protocol for ISOs
  Emby.Server.Implementations/MediaEncoder/EncodingManager.cs
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Labels: stable backport

#5621 enable range processing for download endpoints
  Jellyfin.Api/Controllers/LibraryController.cs
Labels: stable backport

#5629 Fix stream selection having no effect when casting to jellyfin-mpv-shim
  Jellyfin.Api/Controllers/SessionController.cs
Labels: stable backport

#5634 make directoryservice cache case sensitive
  MediaBrowser.Controller/Providers/DirectoryService.cs
  tests/Jellyfin.Controller.Tests/DirectoryServiceTests.cs
  tests/Jellyfin.Controller.Tests/Jellyfin.Controller.Tests.csproj
Labels: stable backport

#5624 Allow subtitle format to be set from query parameter.
  Jellyfin.Api/Controllers/SubtitleController.cs
Labels: stable backport

#5495 Fix remote access whitelist
  Jellyfin.Networking/Manager/NetworkManager.cs
  Jellyfin.Server/Middleware/IpBasedAccessValidationMiddleware.cs
  Jellyfin.sln
  MediaBrowser.Common/Net/INetworkManager.cs
  tests/Jellyfin.Networking.Tests/NetworkParseTests.cs
Labels: stable backport
