Repository jellyfin/jellyfin, pull requests merged in 2021-11, with the labels that each got.

#6745 Use correct id when finding existing dlna profile
  Emby.Dlna/DlnaManager.cs
  Jellyfin.Api/Controllers/DlnaController.cs
  MediaBrowser.Controller/Dlna/IDlnaManager.cs
Labels: bug

#6806 Update to full dotnet 6
  .ci/azure-pipelines-abi.yml
  .ci/azure-pipelines-main.yml
  .ci/azure-pipelines-package.yml
  .ci/azure-pipelines-test.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/openapi.yml
  Directory.Build.props
  Emby.Dlna/Emby.Dlna.csproj
  Emby.Drawing/ImageProcessor.cs
  Emby.Server.Implementations/Emby.Server.Implementations.csproj
  Jellyfin.Api/Controllers/DynamicHlsController.cs
  Jellyfin.Api/Controllers/HlsSegmentController.cs
  Jellyfin.Api/Controllers/ImageByNameController.cs
  Jellyfin.Api/Helpers/ClassMigrationHelper.cs
  Jellyfin.Api/Helpers/StreamingHelpers.cs
  Jellyfin.Api/Helpers/TranscodingJobHelper.cs
  Jellyfin.Api/Jellyfin.Api.csproj
  Jellyfin.Data/Jellyfin.Data.csproj
  Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj
  Jellyfin.Server/Jellyfin.Server.csproj
  MediaBrowser.Common/MediaBrowser.Common.csproj
  MediaBrowser.Controller/Entities/Folder.cs
  MediaBrowser.Controller/MediaBrowser.Controller.csproj
  MediaBrowser.LocalMetadata/Parsers/BaseItemXmlParser.cs
  MediaBrowser.MediaEncoding/MediaBrowser.MediaEncoding.csproj
  MediaBrowser.Model/Dlna/DlnaMaps.cs
  MediaBrowser.Model/Dlna/StreamInfo.cs
  MediaBrowser.Model/MediaBrowser.Model.csproj
  MediaBrowser.Providers/MediaBrowser.Providers.csproj
  MediaBrowser.Providers/MediaInfo/EmbeddedImageProvider.cs
  deployment/Dockerfile.centos.amd64
  deployment/Dockerfile.fedora.amd64
  deployment/Dockerfile.ubuntu.amd64
  deployment/Dockerfile.ubuntu.arm64
  deployment/Dockerfile.ubuntu.armhf
  tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj
  tests/Jellyfin.Server.Integration.Tests/Jellyfin.Server.Integration.Tests.csproj
  tests/Jellyfin.Server.Tests/Jellyfin.Server.Tests.csproj
Labels: dependencies, .NET

#6865 Use the Memory overload for ReadAsync
  Jellyfin.Api/Helpers/ProgressiveFileStream.cs
  Jellyfin.Api/Models/PlaybackDtos/TranscodingJobDto.cs
  Jellyfin.Api/Models/PlaybackDtos/TranscodingThrottler.cs
Labels: needs testing
