Repository jellyfin/jellyfin, pull requests merged in 2022-12, with the labels that each got.

#8836 Add delay_moov flag for progressive mp4 transcoding
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: bug

#8515 feat: macOS arm64 build support
  build.yaml
  deployment/Dockerfile.macos.amd64
  deployment/Dockerfile.macos.arm64
  deployment/build.macos.amd64
  deployment/build.macos.arm64
Labels: hacktoberfest-accepted

#8985 Checkout common ancestor for comparison in OpenAPI workflow
  .github/workflows/openapi.yml
Labels: bug, github_actions, ci, github-actions
