Repository jellyfin/jellyfin, pull requests merged in 2022-06, with the labels that each got.

#7842 Backport all dependency updates
  Emby.Server.Implementations/Emby.Server.Implementations.csproj
  Jellyfin.Api/Jellyfin.Api.csproj
  Jellyfin.Server/Jellyfin.Server.csproj
  MediaBrowser.Model/MediaBrowser.Model.csproj
  MediaBrowser.Providers/MediaBrowser.Providers.csproj
  tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj
  tests/Jellyfin.Common.Tests/Jellyfin.Common.Tests.csproj
  tests/Jellyfin.Controller.Tests/Jellyfin.Controller.Tests.csproj
  tests/Jellyfin.Dlna.Tests/Jellyfin.Dlna.Tests.csproj
  tests/Jellyfin.Extensions.Tests/Jellyfin.Extensions.Tests.csproj
  tests/Jellyfin.MediaEncoding.Hls.Tests/Jellyfin.MediaEncoding.Hls.Tests.csproj
  tests/Jellyfin.MediaEncoding.Keyframes.Tests/Jellyfin.MediaEncoding.Keyframes.Tests.csproj
  tests/Jellyfin.MediaEncoding.Tests/Jellyfin.MediaEncoding.Tests.csproj
  tests/Jellyfin.Model.Tests/Jellyfin.Model.Tests.csproj
  tests/Jellyfin.Naming.Tests/Jellyfin.Naming.Tests.csproj
  tests/Jellyfin.Networking.Tests/Jellyfin.Networking.Tests.csproj
  tests/Jellyfin.Providers.Tests/Jellyfin.Providers.Tests.csproj
  tests/Jellyfin.Server.Implementations.Tests/Jellyfin.Server.Implementations.Tests.csproj
  tests/Jellyfin.Server.Integration.Tests/Jellyfin.Server.Integration.Tests.csproj
  tests/Jellyfin.Server.Tests/Jellyfin.Server.Tests.csproj
  tests/Jellyfin.XbmcMetadata.Tests/Jellyfin.XbmcMetadata.Tests.csproj
Labels: stable backport

#7810 IAsyncDisposable is one big pitfall
  Jellyfin.Server/Program.cs
  MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
Labels: stable backport

#7852 Fix the PNG image decoding issue in Skia
  Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj
Labels: stable backport

#7854 chore: enable on demand keyframe extraction for mkv
  MediaBrowser.Model/Configuration/EncodingOptions.cs
Labels: stable backport

#7867 Don't add `MigrationOptions` to the api spec
  Jellyfin.Server/Filters/AdditionalModelFilter.cs
Labels: stable backport

#7868 chore: disable DLNA by default
  Emby.Dlna/Configuration/DlnaOptions.cs
  Jellyfin.Api/Attributes/DlnaEnabledAttribute.cs
  Jellyfin.Api/Controllers/DlnaServerController.cs
Labels: stable backport

#7892 fix: tv shows do not support multi edition
  Emby.Server.Implementations/Library/Resolvers/Movies/MovieResolver.cs
Labels: stable backport

#7885 Prevent 400 error when using navigation buttons.
  MediaBrowser.Model/Session/GeneralCommand.cs
Labels: stable backport

#7894 Switch to FirstOrDefault extension
  Jellyfin.Api/Controllers/SearchController.cs
  src/Jellyfin.Extensions/ReadOnlyListExtension.cs
Labels: stable backport

#7911 fix: only use keyframes when remuxing video
  Jellyfin.Api/Controllers/DynamicHlsController.cs
  src/Jellyfin.MediaEncoding.Hls/Playlist/CreateMainPlaylistRequest.cs
  src/Jellyfin.MediaEncoding.Hls/Playlist/DynamicHlsPlaylistGenerator.cs
Labels: stable backport

#7913 fix: read configuration during Invoke instead of during construction
  Jellyfin.Server/Middleware/ResponseTimeMiddleware.cs
Labels: stable backport

#7925 Remove MPEG4 hwaccel from AMF
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#7924 Improve AMF tonemap speed when using sw decoding
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#7873 fix: respect the image refresh options when parsing remote images from NFO
  MediaBrowser.Controller/Providers/ImageRefreshOptions.cs
  MediaBrowser.Providers/Manager/MetadataService.cs
Labels: stable backport

#7941 Fix the int overflow issue and the wrong map index of external audio
  Jellyfin.Api/Helpers/DynamicHlsHelper.cs
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#7946 feat: partially handle SVG files and remove exceptions from blurhash and dimensions
  Emby.Drawing/ImageProcessor.cs
  Emby.Server.Implementations/Library/LibraryManager.cs
  Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj
  Jellyfin.Drawing.Skia/SkiaEncoder.cs
  Jellyfin.Drawing.Skia/SkiaHelper.cs
  MediaBrowser.Controller/Drawing/IImageProcessor.cs
Labels: stable backport

#7947 Add VideoRangeType to video conditions
  Emby.Dlna/Didl/DidlBuilder.cs
  Emby.Dlna/PlayTo/PlayToController.cs
  Jellyfin.Api/Helpers/StreamingHelpers.cs
  MediaBrowser.Controller/MediaEncoding/BaseEncodingJobOptions.cs
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.Controller/MediaEncoding/EncodingJobInfo.cs
  MediaBrowser.Model/Dlna/ConditionProcessor.cs
  MediaBrowser.Model/Dlna/ContentFeatureBuilder.cs
  MediaBrowser.Model/Dlna/DeviceProfile.cs
  MediaBrowser.Model/Dlna/ProfileConditionValue.cs
  MediaBrowser.Model/Dlna/StreamBuilder.cs
  MediaBrowser.Model/Dlna/StreamInfo.cs
  MediaBrowser.Model/Entities/MediaStream.cs
  MediaBrowser.Model/Session/TranscodeReason.cs
Labels: stable backport

#7950 Brighter VPP tone-mapping on Intel
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
  MediaBrowser.Model/Configuration/EncodingOptions.cs
Labels: stable backport

#7887 Move service hardening options to override config
  debian/conf/jellyfin.service.conf
  debian/jellyfin.service
Labels: stable backport, awaiting-feedback

#7955 Fix output extension if user has no transcoding permission
  Jellyfin.Api/Helpers/StreamingHelpers.cs
Labels: stable backport

#7960 Fix subtitle encoder if subrip is requested
  MediaBrowser.MediaEncoding/Subtitles/AssWriter.cs
  MediaBrowser.MediaEncoding/Subtitles/SsaWriter.cs
  MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
  MediaBrowser.Model/MediaInfo/SubtitleFormat.cs
Labels: stable backport

#7961 refactor: use season number and episode number for NextUp ordering instead of SortName
  Emby.Server.Implementations/TV/TVSeriesManager.cs
Labels: stable backport, discussion needed

#7984 Upgrade to dotnet 6.0.6, update remaining dependencies
  Emby.Server.Implementations/Emby.Server.Implementations.csproj
  Jellyfin.Api/Jellyfin.Api.csproj
  Jellyfin.Drawing.Skia/Jellyfin.Drawing.Skia.csproj
  Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj
  Jellyfin.Server/Jellyfin.Server.csproj
  MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
  MediaBrowser.Model/MediaBrowser.Model.csproj
  deployment/Dockerfile.centos.amd64
  deployment/Dockerfile.fedora.amd64
  deployment/Dockerfile.ubuntu.amd64
  deployment/Dockerfile.ubuntu.arm64
  deployment/Dockerfile.ubuntu.armhf
  tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj
  tests/Jellyfin.Server.Integration.Tests/Jellyfin.Server.Integration.Tests.csproj
  tests/Jellyfin.Server.Tests/Jellyfin.Server.Tests.csproj
Labels: stable backport

#7988 Catch external streams exceptions
  MediaBrowser.Providers/MediaInfo/AudioResolver.cs
  MediaBrowser.Providers/MediaInfo/FFProbeProvider.cs
  MediaBrowser.Providers/MediaInfo/MediaInfoResolver.cs
  MediaBrowser.Providers/MediaInfo/SubtitleResolver.cs
  tests/Jellyfin.Providers.Tests/MediaInfo/AudioResolverTests.cs
  tests/Jellyfin.Providers.Tests/MediaInfo/MediaInfoResolverTests.cs
  tests/Jellyfin.Providers.Tests/MediaInfo/SubtitleResolverTests.cs
Labels: stable backport

#8001 Fix yuvj420p pixel format hardware decoding
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#7994 Fix the broken transcoding throttler
  Jellyfin.Api/Controllers/DynamicHlsController.cs
  Jellyfin.Api/Controllers/VideosController.cs
  Jellyfin.Api/Helpers/TranscodingJobHelper.cs
  Jellyfin.Api/Models/StreamingDtos/StreamState.cs
  MediaBrowser.Controller/MediaEncoding/JobLogger.cs
Labels: stable backport

#7964 Add DoVi side data parsing
  Emby.Server.Implementations/Data/SqliteItemRepository.cs
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.MediaEncoding/Probing/MediaStreamInfo.cs
  MediaBrowser.MediaEncoding/Probing/MediaStreamInfoSideData.cs
  MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
  MediaBrowser.Model/Entities/MediaStream.cs
  tests/Jellyfin.MediaEncoding.Tests/Probing/ProbeResultNormalizerTests.cs
  tests/Jellyfin.MediaEncoding.Tests/Test Data/Probing/video_metadata.json
Labels: stable backport

#8038 Remove mount and unmount permissions for jellyfin group from sudoers
  debian/conf/jellyfin-sudoers
  fedora/README.md
  fedora/jellyfin.sudoers
Labels: stable backport
