Repository jellyfin/jellyfin, pull requests merged in 2022-03, with the labels that each got.

#7378 Add resume book as default home section
  Jellyfin.Api/Controllers/DisplayPreferencesController.cs
Labels: bug

#7383 Include played and unplayed results in the same next up request
  Emby.Server.Implementations/TV/TVSeriesManager.cs
  Jellyfin.Api/Controllers/TvShowsController.cs
  MediaBrowser.Model/Querying/NextUpQuery.cs
Labels: enhancement

#7396 Update artwork repository urls
  MediaBrowser.Providers/Plugins/StudioImages/Plugin.cs
  MediaBrowser.Providers/Plugins/StudioImages/StudiosImageProvider.cs
Labels: enhancement

#7487 Change DLNA description requests to obey profiles, format UUID correctly
  Emby.Dlna/DlnaManager.cs
  Emby.Dlna/Main/DlnaEntryPoint.cs
Labels: area:dlna

#7496 Fix TranscodeReasons property name
  Jellyfin.Api/Helpers/TranscodingJobHelper.cs
  MediaBrowser.Controller/MediaEncoding/EncodingJobInfo.cs
  MediaBrowser.Model/Session/TranscodingInfo.cs
Labels: regression

#7525 Fix media path saving to wrong library when name duplicated
  Emby.Server.Implementations/Library/LibraryManager.cs
Labels: stable backport

#7527 Remove video file from file list before processing external files
  MediaBrowser.Providers/MediaInfo/MediaInfoResolver.cs
Labels: stable backport

#7519 Add new priority level to ResolverPriority for plugins
  MediaBrowser.Controller/Resolvers/ResolverPriority.cs
Labels: stable backport
