Repository jellyfin/jellyfin, pull requests merged in 2022-10, with the labels that each got.

#8480 Revert "Merge pull request #8298 from lomion0815/fix-data-stream"
  MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
  MediaBrowser.Model/Entities/MediaStreamType.cs
Labels: bug, regression

#8499 chore: add Basque to the list of localization options
  Emby.Server.Implementations/Localization/LocalizationManager.cs
Labels: stable backport

#8500 fix: use HttpContext and ClaimsPrincipal instead of IAuthorizationContext
  Emby.Server.Implementations/ApplicationHost.cs
  Emby.Server.Implementations/HttpServer/Security/SessionContext.cs
  Emby.Server.Implementations/Session/SessionWebSocketListener.cs
  Jellyfin.Api/Auth/BaseAuthorizationHandler.cs
  Jellyfin.Api/Auth/SyncPlayAccessPolicy/SyncPlayAccessHandler.cs
  Jellyfin.Api/Controllers/ArtistsController.cs
  Jellyfin.Api/Controllers/ClientLogController.cs
  Jellyfin.Api/Controllers/CollectionController.cs
  Jellyfin.Api/Controllers/DynamicHlsController.cs
  Jellyfin.Api/Controllers/GenresController.cs
  Jellyfin.Api/Controllers/ImageController.cs
  Jellyfin.Api/Controllers/InstantMixController.cs
  Jellyfin.Api/Controllers/ItemsController.cs
  Jellyfin.Api/Controllers/LibraryController.cs
  Jellyfin.Api/Controllers/LiveTvController.cs
  Jellyfin.Api/Controllers/MediaInfoController.cs
  Jellyfin.Api/Controllers/MoviesController.cs
  Jellyfin.Api/Controllers/MusicGenresController.cs
  Jellyfin.Api/Controllers/PersonsController.cs
  Jellyfin.Api/Controllers/PlaylistsController.cs
  Jellyfin.Api/Controllers/PlaystateController.cs
  Jellyfin.Api/Controllers/QuickConnectController.cs
  Jellyfin.Api/Controllers/SessionController.cs
  Jellyfin.Api/Controllers/StudiosController.cs
  Jellyfin.Api/Controllers/SubtitleController.cs
  Jellyfin.Api/Controllers/SuggestionsController.cs
  Jellyfin.Api/Controllers/SyncPlayController.cs
  Jellyfin.Api/Controllers/TrailersController.cs
  Jellyfin.Api/Controllers/TvShowsController.cs
  Jellyfin.Api/Controllers/UniversalAudioController.cs
  Jellyfin.Api/Controllers/UserController.cs
  Jellyfin.Api/Controllers/UserLibraryController.cs
  Jellyfin.Api/Controllers/UserViewsController.cs
  Jellyfin.Api/Controllers/VideosController.cs
  Jellyfin.Api/Controllers/YearsController.cs
  Jellyfin.Api/Extensions/ClaimsPrincipalExtensions.cs
  Jellyfin.Api/Extensions/DtoExtensions.cs
  Jellyfin.Api/Helpers/AudioHelper.cs
  Jellyfin.Api/Helpers/ClaimHelpers.cs
  Jellyfin.Api/Helpers/DynamicHlsHelper.cs
  Jellyfin.Api/Helpers/MediaInfoHelper.cs
  Jellyfin.Api/Helpers/RequestHelpers.cs
  Jellyfin.Api/Helpers/StreamingHelpers.cs
  Jellyfin.Api/Helpers/TranscodingJobHelper.cs
  MediaBrowser.Controller/Net/ISessionContext.cs
Labels: hacktoberfest-accepted

#8501 fix: set MinIndexNumber for the next up query
  Emby.Server.Implementations/Data/SqliteItemRepository.cs
  Emby.Server.Implementations/TV/TVSeriesManager.cs
  MediaBrowser.Controller/Entities/InternalItemsQuery.cs
Labels: stable backport

#8516 fix: kill ffprobe if keyframe parsing fails
  src/Jellyfin.MediaEncoding.Keyframes/FfProbe/FfProbeKeyframeExtractor.cs
Labels: stable backport

#8411 Allow direct play even if no audio stream is available
  MediaBrowser.Model/Dlna/StreamBuilder.cs
Labels: stable backport

#8521 Skip missing symlink instead of breaking out of directory scan
  Emby.Server.Implementations/Library/LibraryManager.cs
  Emby.Server.Implementations/Library/ResolverHelper.cs
Labels: hacktoberfest-accepted

#8540 Rewrite BaseItem.ModifySortChunks
  MediaBrowser.Controller/Entities/BaseItem.cs
  MediaBrowser.Controller/Properties/AssemblyInfo.cs
  tests/Jellyfin.Controller.Tests/Entities/BaseItemTests.cs
Labels: hacktoberfest-accepted

#8611 Fix TranscodeReasons type in OpenAPI output
  Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
  Jellyfin.Server/Filters/AdditionalModelFilter.cs
Labels: stable backport

#8609 Use Token for SchedulesDirect Images and Image Index
  Emby.Server.Implementations/LiveTv/Listings/SchedulesDirect.cs
Labels: stable backport

#8620 Fix the DG2 HDR TM tearing issue on Windows
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#8667 Enable OMDB plot for non-English languages as fallback
  MediaBrowser.Providers/Plugins/Omdb/OmdbProvider.cs
Labels: stable backport

#8662 fix: use a combination of ParentIndexNumber and IndexNumber to determine next up episodes
  Emby.Server.Implementations/Data/SqliteItemRepository.cs
  Emby.Server.Implementations/TV/TVSeriesManager.cs
  MediaBrowser.Controller/Entities/InternalItemsQuery.cs
Labels: stable backport
