Repository jellyfin/jellyfin, pull requests merged in 2023-03, with the labels that each got.

#9416 Allocate fewer Lists
  Emby.Dlna/ConnectionManager/ConnectionManagerXmlBuilder.cs
  Emby.Dlna/ContentDirectory/ContentDirectoryXmlBuilder.cs
  Emby.Naming/AudioBook/AudioBookListResolver.cs
  Emby.Server.Implementations/Channels/ChannelManager.cs
  Emby.Server.Implementations/Collections/CollectionManager.cs
  Emby.Server.Implementations/Data/SqliteItemRepository.cs
  Emby.Server.Implementations/Dto/DtoService.cs
  Emby.Server.Implementations/Library/LibraryManager.cs
  Emby.Server.Implementations/Library/Resolvers/Audio/AudioResolver.cs
  Emby.Server.Implementations/Library/UserViewManager.cs
  MediaBrowser.Controller/Persistence/IItemRepository.cs
  MediaBrowser.Providers/Manager/ProviderManager.cs
  MediaBrowser.Providers/Playlists/PlaylistItemsProvider.cs
  MediaBrowser.Providers/Plugins/AudioDb/AudioDbArtistImageProvider.cs
  MediaBrowser.Providers/Plugins/MusicBrainz/MusicBrainzAlbumProvider.cs
  MediaBrowser.Providers/Plugins/Omdb/OmdbImageProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/BoxSets/TmdbBoxSetImageProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/BoxSets/TmdbBoxSetProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieImageProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/People/TmdbPersonImageProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/People/TmdbPersonProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbEpisodeImageProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeasonImageProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeriesImageProvider.cs
Labels: breaking change: plugin api

#9429 Adapt Vulkan filtering to 6.0
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: enhancement

#9430 Fix Live TV hardware decoding
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#9422 Fix stream map when using filter_complex with unlabeled output
  Jellyfin.Api/Controllers/DynamicHlsController.cs
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  tests/Jellyfin.MediaEncoding.Tests/EncoderValidatorTests.cs
  tests/Jellyfin.MediaEncoding.Tests/EncoderValidatorTestsData.cs
Labels: stable backport

#9468 Add manual web builds
  Dockerfile
  Dockerfile.arm
  Dockerfile.arm64
Labels: build

#9485 Fix the bitrate scale factor for h264-to-hevc transcoding
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#9433 Backport HWA permissions fix (#9006) to 10.8.z
  debian/postinst
  fedora/jellyfin.spec
Labels: enhancement

#9502 Update workflow actions to specify full version
  .github/workflows/codeql-analysis.yml
  .github/workflows/commands.yml
  .github/workflows/openapi.yml
  .github/workflows/repo-stale.yaml
Labels: dependencies, github_actions, ci

#9529 Add merge conflict comment
  .github/workflows/automation.yml
Labels: github_actions, ci

#9538 Fix nvenc preset order
  CONTRIBUTORS.md
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#9561 Add action to close PRs with merge conflicts
  .github/workflows/repo-stale.yaml
Labels: github_actions
