Repository jellyfin/jellyfin, pull requests merged in 2023-02, with the labels that each got.

#9191 ApplicationHost cleanup
  Emby.Server.Implementations/ApplicationHost.cs
  Emby.Server.Implementations/Channels/ChannelManager.cs
  Jellyfin.Server/Helpers/StartupHelpers.cs
  Jellyfin.Server/Program.cs
  MediaBrowser.Controller/Channels/IChannelManager.cs
  MediaBrowser.Controller/Subtitles/ISubtitleManager.cs
  MediaBrowser.Providers/Subtitles/SubtitleManager.cs
Labels: needs testing, breaking change: plugin api

#8982 Fix backdrop image fetching to prioritize non-language images
  MediaBrowser.Providers/Manager/ItemImageProvider.cs
Labels: regression

#9355 Some VAAPI VPP and OpenCL fixes
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#9351 Fix EqualsAny condition check for int and double
  MediaBrowser.Model/Dlna/ConditionProcessor.cs
Labels: stable backport

#8526 Overhaul content rating handling
  Emby.Server.Implementations/Data/SqliteItemRepository.cs
  Emby.Server.Implementations/Dto/DtoService.cs
  Emby.Server.Implementations/Localization/LocalizationManager.cs
  Emby.Server.Implementations/Localization/Ratings/0-prefer.csv
  Emby.Server.Implementations/Localization/Ratings/au.csv
  Emby.Server.Implementations/Localization/Ratings/be.csv
  Emby.Server.Implementations/Localization/Ratings/br.csv
  Emby.Server.Implementations/Localization/Ratings/ca.csv
  Emby.Server.Implementations/Localization/Ratings/co.csv
  Emby.Server.Implementations/Localization/Ratings/de.csv
  Emby.Server.Implementations/Localization/Ratings/dk.csv
  Emby.Server.Implementations/Localization/Ratings/es.csv
  Emby.Server.Implementations/Localization/Ratings/fi.csv
  Emby.Server.Implementations/Localization/Ratings/fr.csv
  Emby.Server.Implementations/Localization/Ratings/gb.csv
  Emby.Server.Implementations/Localization/Ratings/ie.csv
  Emby.Server.Implementations/Localization/Ratings/jp.csv
  Emby.Server.Implementations/Localization/Ratings/kz.csv
  Emby.Server.Implementations/Localization/Ratings/mx.csv
  Emby.Server.Implementations/Localization/Ratings/nl.csv
  Emby.Server.Implementations/Localization/Ratings/no.csv
  Emby.Server.Implementations/Localization/Ratings/nz.csv
  Emby.Server.Implementations/Localization/Ratings/ro.csv
  Emby.Server.Implementations/Localization/Ratings/ru.csv
  Emby.Server.Implementations/Localization/Ratings/se.csv
  Emby.Server.Implementations/Localization/Ratings/uk.csv
  Emby.Server.Implementations/Localization/Ratings/us.csv
  Jellyfin.Api/Controllers/ItemUpdateController.cs
  Jellyfin.Api/Controllers/ItemsController.cs
  Jellyfin.Api/Controllers/UserLibraryController.cs
  Jellyfin.Server/Migrations/MigrationRunner.cs
  Jellyfin.Server/Migrations/PreStartupRoutines/MigrateRatingLevels.cs
  MediaBrowser.Controller/Entities/BaseItem.cs
  MediaBrowser.Model/Entities/ParentalRating.cs
  MediaBrowser.Model/Users/UserPolicy.cs
  tests/Jellyfin.Server.Implementations.Tests/Localization/LocalizationManagerTests.cs
Labels: hacktoberfest-accepted

#9391 Fix H.264 baseline hwaccel and enable enhanced Nvdec by default
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.Model/Configuration/EncodingOptions.cs
Labels: stable backport

#9402 Improve the Vulkan based subtitle burn-in performance
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: enhancement
