Repository jellyfin/jellyfin, pull requests merged in 2023-12, with the labels that each got.

#10660 Move Jellyfin.Networking
  Emby.Server.Implementations/ApplicationHost.cs
  Emby.Server.Implementations/Emby.Server.Implementations.csproj
  Emby.Server.Implementations/EntryPoints/ExternalPortForwarding.cs
  Emby.Server.Implementations/EntryPoints/UdpServerEntryPoint.cs
  Emby.Server.Implementations/Net/SocketFactory.cs
  Emby.Server.Implementations/Udp/UdpServer.cs
  Jellyfin.Api/Jellyfin.Api.csproj
  Jellyfin.Networking/HappyEyeballs/HttpClientExtension.cs
  Jellyfin.Networking/Jellyfin.Networking.csproj
  Jellyfin.Networking/Manager/NetworkManager.cs
  Jellyfin.sln
  src/Jellyfin.Networking/ExternalPortForwarding.cs
  src/Jellyfin.Networking/HappyEyeballs/HttpClientExtension.cs
  src/Jellyfin.Networking/Jellyfin.Networking.csproj
  src/Jellyfin.Networking/Manager/NetworkManager.cs
  src/Jellyfin.Networking/Udp/SocketFactory.cs
  src/Jellyfin.Networking/Udp/UdpServer.cs
  src/Jellyfin.Networking/UdpServerEntryPoint.cs
  tests/Jellyfin.Networking.Tests/Jellyfin.Networking.Tests.csproj
Labels: enhancement, backend

#10710 Use `eof_action=pass` when overlaying subtitles
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: enhancement, good first issue, backend

#10573 Add new API endpoint to view/update Item UserData
  Emby.Server.Implementations/Library/UserDataManager.cs
  Jellyfin.Api/Controllers/ItemsController.cs
  MediaBrowser.Controller/Library/IUserDataManager.cs
  MediaBrowser.Model/Dto/UpdateUserItemDataDto.cs
  MediaBrowser.Model/Entities/UserDataSaveReason.cs
Labels: backend, feature

#10702 Convert CollectionType to use lowercase enum names
  Emby.Server.Implementations/Images/CollectionFolderImageProvider.cs
  Emby.Server.Implementations/Images/DynamicImageProvider.cs
  Emby.Server.Implementations/Library/LibraryManager.cs
  Emby.Server.Implementations/Library/Resolvers/Audio/AudioResolver.cs
  Emby.Server.Implementations/Library/Resolvers/Audio/MusicAlbumResolver.cs
  Emby.Server.Implementations/Library/Resolvers/Audio/MusicArtistResolver.cs
  Emby.Server.Implementations/Library/Resolvers/Books/BookResolver.cs
  Emby.Server.Implementations/Library/Resolvers/Movies/MovieResolver.cs
  Emby.Server.Implementations/Library/Resolvers/PhotoAlbumResolver.cs
  Emby.Server.Implementations/Library/Resolvers/PhotoResolver.cs
  Emby.Server.Implementations/Library/Resolvers/PlaylistResolver.cs
  Emby.Server.Implementations/Library/Resolvers/TV/EpisodeResolver.cs
  Emby.Server.Implementations/Library/Resolvers/TV/SeriesResolver.cs
  Emby.Server.Implementations/Library/UserViewManager.cs
  Emby.Server.Implementations/LiveTv/LiveTvManager.cs
  Emby.Server.Implementations/Playlists/PlaylistsFolder.cs
  Jellyfin.Api/Controllers/GenresController.cs
  Jellyfin.Api/Controllers/ItemUpdateController.cs
  Jellyfin.Api/Controllers/ItemsController.cs
  Jellyfin.Api/Controllers/LibraryController.cs
  Jellyfin.Data/Enums/CollectionType.cs
  MediaBrowser.Controller/Entities/BaseItem.cs
  MediaBrowser.Controller/Entities/UserView.cs
  MediaBrowser.Controller/Entities/UserViewBuilder.cs
  tests/Jellyfin.Server.Implementations.Tests/Library/AudioResolverTests.cs
  tests/Jellyfin.Server.Implementations.Tests/Library/EpisodeResolverTest.cs
Labels: backend

#10422 Update /Device endpoint to return CustomName
  Jellyfin.Server.Implementations/Devices/DeviceManager.cs
  MediaBrowser.Model/Devices/DeviceInfo.cs
Labels: enhancement, backend, ui & ux

#10672 Quote bash paths to prevent word splitting
  deployment/build.centos.amd64
  deployment/build.debian.amd64
  deployment/build.debian.arm64
  deployment/build.debian.armhf
  deployment/build.fedora.amd64
  deployment/build.linux.amd64
  deployment/build.linux.amd64-musl
  deployment/build.linux.arm64
  deployment/build.linux.armhf
  deployment/build.linux.musl-linux-arm64
  deployment/build.macos.amd64
  deployment/build.macos.arm64
  deployment/build.portable
  deployment/build.ubuntu.amd64
  deployment/build.ubuntu.arm64
  deployment/build.ubuntu.armhf
  deployment/build.windows.amd64
Labels: bug, build

#10682 Fix some warnings in LiveTV
  Emby.Server.Implementations/Library/ExclusiveLiveStream.cs
  Emby.Server.Implementations/LiveTv/EmbyTV/DirectRecorder.cs
  Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs
  Emby.Server.Implementations/LiveTv/EmbyTV/EncodedRecorder.cs
  Emby.Server.Implementations/LiveTv/EmbyTV/IRecorder.cs
  Emby.Server.Implementations/LiveTv/Listings/SchedulesDirect.cs
  Emby.Server.Implementations/LiveTv/Listings/XmlTvListingsProvider.cs
  Emby.Server.Implementations/LiveTv/LiveTvManager.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/BaseTunerHost.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/DiscoverResponse.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/LiveStream.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/M3UTunerHost.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/M3uParser.cs
  Emby.Server.Implementations/LiveTv/TunerHosts/SharedHttpStream.cs
  MediaBrowser.Controller/Library/ILiveStream.cs
  MediaBrowser.Controller/LiveTv/ITunerHost.cs
Labels: build, backend

#10737 Make TMDb api key configurable, fix missing/wrong image urls
  MediaBrowser.Providers/Plugins/Tmdb/BoxSets/TmdbBoxSetProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/Configuration/PluginConfiguration.cs
  MediaBrowser.Providers/Plugins/Tmdb/Configuration/config.html
  MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/TmdbClientManager.cs
Labels: enhancement, backend
