Repository jellyfin/jellyfin, pull requests merged in 2023-09, with the labels that each got.

#10183 Fix AV1 playback in LiveTV
  Jellyfin.Api/Controllers/DynamicHlsController.cs
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: enhancement

#10199 Fix AV1 NVENC encoder profile option
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: enhancement

#10197 Remove one session per device id limitation
  Emby.Server.Implementations/Session/SessionManager.cs
Labels: enhancement

#10200 Add option to include resumable items in next up requests
  Emby.Server.Implementations/TV/TVSeriesManager.cs
  Jellyfin.Api/Controllers/TvShowsController.cs
  MediaBrowser.Model/Querying/NextUpQuery.cs
Labels: enhancement

#10217 Run collect script on failures
  .ci/azure-pipelines-package.yml
Labels: build, ci

#6209 add auto-bump_version workflow
  .github/workflows/repo-bump-version.yaml
Labels: future

#10275 Fix A53 CC SEI breaking H26x_VAAPI hardware encode
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: enhancement

#10305 Update node versions
  Dockerfile
  Dockerfile.arm
  Dockerfile.arm64
Labels: build
