Repository jellyfin/jellyfin, pull requests merged in 2023-01, with the labels that each got.

#9060 Disable splash screen image by default
  MediaBrowser.Model/Branding/BrandingOptions.cs
Labels: enhancement, stable backport

#9050 Update workaround for i915 hang in linux 5.18 to 6.1.3
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#9092 Don't add additional entries if HEVC encoding is disabled
  Jellyfin.Api/Helpers/DynamicHlsHelper.cs
Labels: stable backport

#9051 Fix transcode reasons
  MediaBrowser.Model/Dlna/StreamBuilder.cs
  tests/Jellyfin.Model.Tests/Dlna/StreamBuilderTests.cs
Labels: bug, stable backport

#9068 Remove DvdLib
  DvdLib/BigEndianBinaryReader.cs
  DvdLib/DvdLib.csproj
  DvdLib/Ifo/Cell.cs
  DvdLib/Ifo/CellPlaybackInfo.cs
  DvdLib/Ifo/CellPositionInfo.cs
  DvdLib/Ifo/Chapter.cs
  DvdLib/Ifo/Dvd.cs
  DvdLib/Ifo/DvdTime.cs
  DvdLib/Ifo/Program.cs
  DvdLib/Ifo/ProgramChain.cs
  DvdLib/Ifo/Title.cs
  DvdLib/Ifo/UserOperation.cs
  DvdLib/Properties/AssemblyInfo.cs
  Emby.Server.Implementations/ApplicationHost.cs
  Jellyfin.sln
  MediaBrowser.Controller/MediaEncoding/IMediaEncoder.cs
  MediaBrowser.MediaEncoding/BdInfo/BdInfoDirectoryInfo.cs
  MediaBrowser.MediaEncoding/BdInfo/BdInfoExaminer.cs
  MediaBrowser.MediaEncoding/BdInfo/BdInfoFileInfo.cs
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
  MediaBrowser.MediaEncoding/MediaBrowser.MediaEncoding.csproj
  MediaBrowser.Model/MediaInfo/BlurayDiscInfo.cs
  MediaBrowser.Model/MediaInfo/IBlurayExaminer.cs
  MediaBrowser.Providers/MediaBrowser.Providers.csproj
  MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs
  MediaBrowser.Providers/MediaInfo/ProbeProvider.cs
Labels: discussion needed, needs testing

#9145 Fix PGS position issue in sw decoding #8602
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#9178 Escape the path to pass as a command line argument
  Jellyfin.Api/Controllers/DynamicHlsController.cs
  Jellyfin.Api/Jellyfin.Api.csproj
  MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs
  MediaBrowser.MediaEncoding/Encoder/EncodingUtils.cs
Labels: stable backport
