Repository jellyfin/jellyfin, pull requests merged in 2024-07, with the labels that each got.

#12270 Add software tonemap filter support
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Labels: feature, release-highlight

#12240 Fix season handling ("Season Unknown" / unneccesary empty seasons)
  MediaBrowser.Controller/Entities/TV/Series.cs
Labels: stable backport

#12226 Use real temp dir instead of cache dir for temp files
  Emby.Server.Implementations/AppBase/BaseApplicationPaths.cs
  Emby.Server.Implementations/IO/ManagedFileSystem.cs
  Emby.Server.Implementations/Images/BaseDynamicImageProvider.cs
  Emby.Server.Implementations/ScheduledTasks/Tasks/AudioNormalizationTask.cs
  Jellyfin.Server.Implementations/Trickplay/TrickplayManager.cs
  Jellyfin.Server/Helpers/StartupHelpers.cs
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
  MediaBrowser.MediaEncoding/Transcoding/TranscodeManager.cs
  src/Jellyfin.Drawing.Skia/SkiaEncoder.cs
Labels: release-highlight

#12274 Add check for ProviderIds to prevent '=' from appearing in keys, also support '=' in the values.
  Emby.Server.Implementations/Data/SqliteItemRepository.cs
  MediaBrowser.Model/Entities/ProviderIdsExtensions.cs
  tests/Jellyfin.Model.Tests/Entities/ProviderIdsExtensionsTests.cs
Labels: breaking change: plugin api

#12278 Fix localization of audio title
  Emby.Server.Implementations/Data/SqliteItemRepository.cs
  MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
  tests/Jellyfin.MediaEncoding.Tests/Probing/ProbeResultNormalizerTests.cs
Labels: stable backport

#12279 Move external url listing to provider for plugin use
  Emby.Server.Implementations/ApplicationHost.cs
  MediaBrowser.Controller/Entities/BaseItem.cs
  MediaBrowser.Controller/Entities/Movies/Movie.cs
  MediaBrowser.Controller/Entities/TV/Episode.cs
  MediaBrowser.Controller/Entities/TV/Series.cs
  MediaBrowser.Controller/Entities/Trailer.cs
  MediaBrowser.Controller/LiveTv/LiveTvProgram.cs
  MediaBrowser.Controller/Providers/IExternalId.cs
  MediaBrowser.Controller/Providers/IExternalUrlProvider.cs
  MediaBrowser.Controller/Providers/IProviderManager.cs
  MediaBrowser.Model/Providers/ExternalIdInfo.cs
  MediaBrowser.Providers/Manager/ProviderManager.cs
  tests/Jellyfin.Providers.Tests/Manager/ProviderManagerTests.cs
Labels: breaking change: plugin api

#11511 Add option to extract keyframe only during trickplay image generation
  Jellyfin.Server.Implementations/Trickplay/TrickplayManager.cs
  MediaBrowser.Controller/MediaEncoding/IMediaEncoder.cs
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
  MediaBrowser.Model/Configuration/TrickplayOptions.cs
Labels: enhancement

#11489 Add remuxing support for VP9
  Jellyfin.Api/Helpers/DynamicHlsHelper.cs
  Jellyfin.Api/Helpers/HlsCodecStringHelpers.cs
  MediaBrowser.Model/Dlna/StreamBuilder.cs
Labels: enhancement

#12296 Properly escape paths in concat file for BDMV
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Labels: stable backport

#11486 Enable Dolby AC-4 decoder
  Jellyfin.Api/Controllers/DynamicHlsController.cs
  MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
Labels: feature

#11510 Enable hardware Trickplay processing pipeline for VideoToolbox
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Labels: enhancement

#11399 Add audio remux to UniversalAudioController
  Jellyfin.Api/Controllers/UniversalAudioController.cs
  Jellyfin.Api/Helpers/DynamicHlsHelper.cs
  MediaBrowser.MediaEncoding/Transcoding/TranscodeManager.cs
  MediaBrowser.Model/Dlna/StreamBuilder.cs
Labels: enhancement

#11901 Implement Device Cache to replace EFCoreSecondLevelCacheInterceptor
  Directory.Packages.props
  Emby.Server.Implementations/ConfigurationOptions.cs
  Emby.Server.Implementations/Session/SessionManager.cs
  Jellyfin.Api/Controllers/DevicesController.cs
  Jellyfin.Server.Implementations/Devices/DeviceManager.cs
  Jellyfin.Server.Implementations/Extensions/ServiceCollectionExtensions.cs
  Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj
  Jellyfin.Server.Implementations/Security/AuthorizationContext.cs
  Jellyfin.Server.Implementations/Users/DeviceAccessHost.cs
  Jellyfin.Server/Extensions/WebHostBuilderExtensions.cs
  Jellyfin.Server/Startup.cs
  MediaBrowser.Controller/Devices/IDeviceManager.cs
  MediaBrowser.Controller/Extensions/ConfigurationExtensions.cs
Labels: stable backport

#11492 Add better audio VBR settings
  Jellyfin.Api/Controllers/AudioController.cs
  Jellyfin.Api/Controllers/DynamicHlsController.cs
  Jellyfin.Api/Controllers/UniversalAudioController.cs
  Jellyfin.Api/Controllers/VideosController.cs
  MediaBrowser.Controller/MediaEncoding/BaseEncodingJobOptions.cs
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.Controller/MediaEncoding/EncodingJobInfo.cs
  MediaBrowser.Model/Dlna/StreamBuilder.cs
  MediaBrowser.Model/Dlna/StreamInfo.cs
  MediaBrowser.Model/Dlna/TranscodingProfile.cs
Labels: enhancement

#12295 Add TrySetProviderId extension
  Emby.Server.Implementations/Library/Resolvers/Movies/BoxSetResolver.cs
  Emby.Server.Implementations/Library/Resolvers/Movies/MovieResolver.cs
  Emby.Server.Implementations/Library/Resolvers/TV/SeriesResolver.cs
  MediaBrowser.LocalMetadata/Parsers/BaseItemXmlParser.cs
  MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
  MediaBrowser.Model/Entities/ProviderIdsExtensions.cs
  MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
  MediaBrowser.Providers/Plugins/Omdb/OmdbProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/People/TmdbPersonProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbEpisodeProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeasonProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeriesProvider.cs
  MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs
  MediaBrowser.XbmcMetadata/Parsers/MovieNfoParser.cs
  MediaBrowser.XbmcMetadata/Parsers/SeriesNfoParser.cs
  src/Jellyfin.LiveTv/Guide/GuideManager.cs
Labels: breaking change: plugin api

#11879 Migrate to z440.atl from TagLib-Sharp
  Directory.Packages.props
  MediaBrowser.Providers/MediaBrowser.Providers.csproj
  MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
Labels: needs testing

#12356 Fix creating virtual seasons (again)
  MediaBrowser.Providers/TV/SeriesMetadataService.cs
Labels: stable backport
