Repository jellyfin/jellyfin, pull requests merged in 2024-01, with the labels that each got.

#10810 Use -noauto{scale,rotate} for disabling auto filters
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: enhancement

#10793 Auto Discovery Cleanup
  Jellyfin.Server/Startup.cs
  src/Jellyfin.Networking/AutoDiscoveryHost.cs
  src/Jellyfin.Networking/Udp/UdpServer.cs
  src/Jellyfin.Networking/UdpServerEntryPoint.cs
Labels: backend

#10324 Feature/enable gh codespaces
  .devcontainer/devcontainer.json
  .vscode/extensions.json
  README.md
Labels: build, platform

#10781 Remove UserManager Cache
  Jellyfin.Server.Implementations/Users/UserManager.cs
  Jellyfin.Server/CoreAppHost.cs
Labels: enhancement, backend, breaking change: plugin api, area:database

#10396 Add nuget.config file to fix NU1507 by only allowing nuget.org as package source. see: https://learn.microsoft.com/en-us/nuget/consume-packages/package-source-mapping and https://github.com/dotnet/sdk/issues/25379
  nuget.config
Labels: build

#10566 Add option to use replaygain tags for audio
  MediaBrowser.Model/Configuration/LibraryOptions.cs
  MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
Labels: backend, feature

#10613 Fixed disposable not being called
  Emby.Server.Implementations/Session/SessionManager.cs
  MediaBrowser.Controller/Session/ISessionManager.cs
  MediaBrowser.Controller/Session/SessionInfo.cs
Labels: bug, backend

#10858 Add ITunerHostManager service and minor LiveTv cleanup
  Emby.Server.Implementations/ApplicationHost.cs
  Jellyfin.Api/Controllers/LiveTvController.cs
  Jellyfin.Server/CoreAppHost.cs
  Jellyfin.Server/Startup.cs
  MediaBrowser.Controller/Channels/IChannelManager.cs
  MediaBrowser.Controller/LiveTv/ILiveTvManager.cs
  MediaBrowser.Controller/LiveTv/ILiveTvService.cs
  MediaBrowser.Controller/LiveTv/ITunerHost.cs
  MediaBrowser.Controller/LiveTv/ITunerHostManager.cs
  MediaBrowser.Controller/LiveTv/LiveTvServiceStatusInfo.cs
  MediaBrowser.Controller/LiveTv/LiveTvTunerInfo.cs
  MediaBrowser.Controller/LiveTv/RecordingInfo.cs
  MediaBrowser.Controller/LiveTv/RecordingStatusChangedEventArgs.cs
  MediaBrowser.Model/IO/IStreamHelper.cs
  MediaBrowser.Model/LiveTv/LiveTvTunerStatus.cs
  src/Jellyfin.LiveTv/Channels/ChannelManager.cs
  src/Jellyfin.LiveTv/Configuration/LiveTvConfigurationExtensions.cs
  src/Jellyfin.LiveTv/Configuration/LiveTvConfigurationFactory.cs
  src/Jellyfin.LiveTv/EmbyTV/EmbyTV.cs
  src/Jellyfin.LiveTv/Extensions/LiveTvServiceCollectionExtensions.cs
  src/Jellyfin.LiveTv/LiveTvConfigurationFactory.cs
  src/Jellyfin.LiveTv/LiveTvManager.cs
  src/Jellyfin.LiveTv/RefreshGuideScheduledTask.cs
  src/Jellyfin.LiveTv/StreamHelper.cs
  src/Jellyfin.LiveTv/TunerHosts/BaseTunerHost.cs
  src/Jellyfin.LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs
  src/Jellyfin.LiveTv/TunerHosts/M3UTunerHost.cs
  src/Jellyfin.LiveTv/TunerHosts/TunerHostManager.cs
Labels: breaking change: plugin api

#10603 Refactor Dockerfile and build
  CONTRIBUTORS.md
  Dockerfile
  Dockerfile.arm
  Dockerfile.arm64
  bump_version
  debian/rules
  deployment/Dockerfile.centos.amd64
  deployment/Dockerfile.debian.amd64
  deployment/Dockerfile.debian.arm64
  deployment/Dockerfile.debian.armhf
  deployment/Dockerfile.docker.amd64
  deployment/Dockerfile.docker.arm64
  deployment/Dockerfile.docker.armhf
  deployment/Dockerfile.fedora.amd64
  deployment/Dockerfile.linux.amd64
  deployment/Dockerfile.linux.amd64-musl
  deployment/Dockerfile.linux.arm64
  deployment/Dockerfile.linux.armhf
  deployment/Dockerfile.linux.musl-linux-arm64
  deployment/Dockerfile.macos.amd64
  deployment/Dockerfile.macos.arm64
  deployment/Dockerfile.portable
  deployment/Dockerfile.ubuntu.amd64
  deployment/Dockerfile.ubuntu.arm64
  deployment/Dockerfile.ubuntu.armhf
  deployment/Dockerfile.windows.amd64
  deployment/build.centos.amd64
  deployment/build.debian.amd64
  deployment/build.debian.arm64
  deployment/build.debian.armhf
  deployment/build.fedora.amd64
  deployment/build.linux.amd64
  deployment/build.linux.amd64-musl
  deployment/build.linux.arm64
  deployment/build.linux.armhf
  deployment/build.linux.musl-linux-arm64
  deployment/build.macos.amd64
  deployment/build.macos.arm64
  deployment/build.portable
  deployment/build.ubuntu.amd64
  deployment/build.ubuntu.arm64
  deployment/build.ubuntu.armhf
  deployment/build.windows.amd64
  fedora/README.md
  fedora/jellyfin.spec
Labels: build, platform, awaiting-feedback

#10924 Fixed some issues in PGSSUB and ASS subtitle burn-in
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
Labels: bug, enhancement
