Repository jellyfin/jellyfin, pull requests merged in 2024-03, with the labels that each got.

#11074 Move userId in API from route to optional query parameter
  Jellyfin.Api/Controllers/ImageController.cs
  Jellyfin.Api/Controllers/ItemsController.cs
  Jellyfin.Api/Controllers/PlaystateController.cs
  Jellyfin.Api/Controllers/SuggestionsController.cs
  Jellyfin.Api/Controllers/UserController.cs
  Jellyfin.Api/Controllers/UserLibraryController.cs
  Jellyfin.Api/Controllers/UserViewsController.cs
Labels: enhancement

#11100 Add migration for new plugin repo
  Jellyfin.Server/Migrations/MigrationRunner.cs
  Jellyfin.Server/Migrations/Routines/UpdateDefaultPluginRepository.cs
  tests/Jellyfin.Server.Implementations.Tests/Test Data/Updates/manifest.json
  tests/Jellyfin.Server.Implementations.Tests/Updates/InstallationManagerTests.cs
Labels: area:database

#10153 Add MediaStreamProtocol enum
  Jellyfin.Api/Controllers/UniversalAudioController.cs
  Jellyfin.Data/Enums/MediaStreamProtocol.cs
  MediaBrowser.Model/Dlna/StreamBuilder.cs
  MediaBrowser.Model/Dlna/StreamInfo.cs
  MediaBrowser.Model/Dlna/TranscodingProfile.cs
  MediaBrowser.Model/Dto/MediaSourceInfo.cs
  MediaBrowser.Providers/Plugins/Omdb/JsonOmdbNotAvailableStringConverter.cs
  src/Jellyfin.Extensions/Json/Converters/JsonDefaultStringEnumConverter.cs
  src/Jellyfin.Extensions/Json/Converters/JsonDefaultStringEnumConverterFactory.cs
  src/Jellyfin.Extensions/Json/Converters/JsonGuidConverter.cs
  src/Jellyfin.Extensions/Json/Converters/JsonNullableStructConverter.cs
  src/Jellyfin.Extensions/Json/JsonDefaults.cs
  src/Jellyfin.Extensions/Json/Utf8JsonExtensions.cs
  tests/Jellyfin.Extensions.Tests/Json/Converters/JsonDefaultStringEnumConverterTests.cs
  tests/Jellyfin.Model.Tests/Dlna/StreamBuilderTests.cs
Labels: enhancement, backend

#11014 feat: Fully support hardware filters on Apple VideoToolbox
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
  MediaBrowser.Model/Configuration/EncodingOptions.cs
Labels: backend, feature, platform, needs testing, release-highlight

#11119 Cleanup PhotoProvider.cs using new .NET 8 features
  Emby.Photos/PhotoProvider.cs
Labels: backend

#11126 Lowercase MediaStreamProtocol for backwards compatibility
  Jellyfin.Api/Controllers/UniversalAudioController.cs
  Jellyfin.Data/Enums/MediaStreamProtocol.cs
  MediaBrowser.Model/Dlna/StreamBuilder.cs
  MediaBrowser.Model/Dlna/StreamInfo.cs
  MediaBrowser.Model/Dlna/TranscodingProfile.cs
  tests/Jellyfin.Extensions.Tests/Json/Converters/JsonDefaultStringEnumConverterTests.cs
  tests/Jellyfin.Model.Tests/Dlna/StreamBuilderTests.cs
Labels: bug, backend

#11129 Specify file as concat when extracting attachments
  MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs
Labels: bug, backend

#11127 Don't attempt to calculate blurhash for svg
  src/Jellyfin.Drawing.Skia/SkiaEncoder.cs
Labels: bug, backend

#11160 Add LSR/CITY to artist whitelist
  MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
Labels: enhancement, backend

#11156 Change parsing logic of audio track title
  MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
Labels: bug, backend

#11155 Fix parsing of audio PremiereDate property
  MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
Labels: bug, good first issue, backend

#11037 Add ability to enable/disable libraries
  CONTRIBUTORS.md
  MediaBrowser.Controller/Entities/CollectionFolder.cs
  MediaBrowser.Model/Configuration/LibraryOptions.cs
Labels: enhancement, good first issue, question

#11165 Catch delete encoded media file exceptions
  MediaBrowser.MediaEncoding/Transcoding/TranscodeManager.cs
Labels: enhancement, good first issue, backend

#11149 Enable nullable for more files
  Emby.Server.Implementations/ApplicationHost.cs
  Emby.Server.Implementations/Devices/DeviceId.cs
  Emby.Server.Implementations/Library/LiveStreamHelper.cs
  Emby.Server.Implementations/Library/MusicManager.cs
  Emby.Server.Implementations/Library/SearchEngine.cs
  MediaBrowser.Controller/Channels/IHasCacheKey.cs
  MediaBrowser.Controller/Channels/ISearchableChannel.cs
  MediaBrowser.Controller/Channels/ISupportsLatestMedia.cs
  MediaBrowser.Controller/Library/IMusicManager.cs
  MediaBrowser.Model/Search/SearchQuery.cs
  MediaBrowser.Model/System/LogFile.cs
  src/Jellyfin.LiveTv/Channels/ChannelManager.cs
Labels: enhancement, backend

#11163 Add lyric files to supported extensions
  MediaBrowser.Controller/Entities/BaseItem.cs
Labels: bug, good first issue, backend

#11154 Add a github action to automatically precheck new issues for problems
  .github/workflows/issue-template-check.yml
Labels: github-actions

#11120 IIS Hosting
  Jellyfin.Server/Program.cs
Labels: feature, discussion needed, needs testing

#9291 fix: skip library folders that are inaccessible or empty
  Emby.Server.Implementations/IO/ManagedFileSystem.cs
  MediaBrowser.Controller/Entities/Folder.cs
  MediaBrowser.Controller/Providers/DirectoryService.cs
  MediaBrowser.Controller/Providers/IDirectoryService.cs
Labels: needs testing

#10469 Add new VideoRangeTypes to fully support DoVi on webOS
  CONTRIBUTORS.md
  Jellyfin.Api/Controllers/DynamicHlsController.cs
  Jellyfin.Data/Enums/VideoRangeType.cs
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.Model/Entities/MediaStream.cs
Labels: good first issue, backend, feature, awaiting-feedback

#11203 Fix codec vs ActualOutputVideoCodec
  Jellyfin.Api/Controllers/DynamicHlsController.cs
Labels: bug

#11178 Adds rename command to commands.yml
  .github/workflows/commands.yml
Labels: github-actions

#11232 Fix default values missing in ClientCapabilities(Dto)
  Jellyfin.Api/Models/SessionDtos/ClientCapabilitiesDto.cs
  MediaBrowser.Model/Session/ClientCapabilities.cs
Labels: regression

#11243 Fix the broken codecs shifting
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: bug

#11249 Support "extra" folder for extras content
  Emby.Naming/Common/NamingOptions.cs
Labels: enhancement

#11268 Remove SessionInfo.FullNowPlayingItem from API responses
  MediaBrowser.Controller/Session/SessionInfo.cs
Labels: bug

#11261 Use enum for BaseItemDto.ExtraType
  Emby.Server.Implementations/Dto/DtoService.cs
  MediaBrowser.Model/Dto/BaseItemDto.cs
Labels: enhancement

#11260 Fix FindExtras overwriting current extra type
  Emby.Server.Implementations/Library/LibraryManager.cs
Labels: bug
