Repository jellyfin/jellyfin, pull requests merged in 2024-04, with the labels that each got.

#11236 Fix disabled libraries being returned in MediaFolders api
  Jellyfin.Api/Controllers/LibraryController.cs
Labels: bug

#11109 Don't decode animated images
  src/Jellyfin.Drawing.Skia/SkiaEncoder.cs
Labels: backend

#11311 #11289 Fixed cleanup task not checking for folders
  Emby.Server.Implementations/ScheduledTasks/Tasks/CleanupCollectionAndPlaylistPathsTask.cs
Labels: bug

#11436 Require elevation for plugin related endpoints
  Jellyfin.Api/Controllers/DashboardController.cs
  Jellyfin.Api/Controllers/PackageController.cs
  Jellyfin.Api/Controllers/PluginsController.cs
Labels: security, breaking change: web api
