Repository jellyfin/jellyfin, pull requests merged in 2024-09, with the labels that each got.

#12550 Create and use FormattingStreamWriter
  MediaBrowser.Controller/Entities/TV/Episode.cs
  MediaBrowser.Controller/Entities/UserViewBuilder.cs
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
  src/Jellyfin.Extensions/FormattingStreamWriter.cs
  tests/Jellyfin.Extensions.Tests/FormattingStreamWriterTests.cs
Labels: stable backport

#12558 Fix alt version name generation
  MediaBrowser.Controller/Entities/BaseItem.cs
  tests/Jellyfin.Controller.Tests/Entities/BaseItemTests.cs
Labels: stable backport

#12562 Use filtered codecs to build appliedConditions
  MediaBrowser.Model/Dlna/StreamBuilder.cs
Labels: stable backport

#10826 Use frozen collections in MimeTypes.cs
  Emby.Server.Implementations/Library/LibraryManager.cs
  MediaBrowser.Model/Net/MimeTypes.cs
Labels: backend

#12594 ABI Diff action - use Github Token
  .github/workflows/ci-compat.yml
Labels: merge conflict

#12479 Add subtitle parser errors to log if available
  CONTRIBUTORS.md
  MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs
  MediaBrowser.MediaEncoding/Subtitles/SubtitleFormatExtensions.cs
Labels: enhancement, backend

#12592 Add native VPP tonemap for QSV on Windows
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: enhancement

#12590 Enable the new BWDIF CUDA deint filter when available
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
Labels: enhancement

#12605 Add SUPPLEMENTAL-CODECS for Dolby Vision video with fallbacks
  Jellyfin.Api/Helpers/DynamicHlsHelper.cs
Labels: enhancement

#12575 Fix subtitle and attachment extraction when input path contains quotes
  MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs
  MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
Labels: stable backport

#12359 Feature/media segments plugin api
  CONTRIBUTORS.md
  Emby.Server.Implementations/Localization/Core/en-US.json
  Emby.Server.Implementations/ScheduledTasks/Tasks/MediaSegmentExtractionTask.cs
  Jellyfin.Server.Implementations/MediaSegments/MediaSegmentManager.cs
  MediaBrowser.Controller/MediaSegements/IMediaSegmentManager.cs
  MediaBrowser.Controller/MediaSegements/IMediaSegmentProvider.cs
  MediaBrowser.Model/Configuration/LibraryOptions.cs
  MediaBrowser.Model/Configuration/MetadataPluginType.cs
  MediaBrowser.Model/MediaSegments/MediaSegmentGenerationRequest.cs
  MediaBrowser.Providers/Manager/ProviderManager.cs
  tests/Jellyfin.Providers.Tests/Manager/ProviderManagerTests.cs
Labels: backend, feature, release-highlight

#12610 Enable Rockchip MJPEG encoder for Trickplay
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Labels: enhancement

#10684 Watch library directories with perm errors
  Emby.Server.Implementations/IO/LibraryMonitor.cs
Labels: bug, backend, needs testing

#12679 Fix DeviceProfile.Id should be nullable
  MediaBrowser.Model/Dlna/DeviceProfile.cs
  MediaBrowser.Model/Dlna/StreamBuilder.cs
Labels: bug
