Repository jellyfin/jellyfin, pull requests merged in 2024-08, with the labels that each got.

#12374 Fix compatibility between TranscodingThrottler and FFmpeg 7.0
  MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
  MediaBrowser.MediaEncoding/Transcoding/TranscodeManager.cs
  tests/Jellyfin.MediaEncoding.Tests/EncoderValidatorTests.cs
  tests/Jellyfin.MediaEncoding.Tests/EncoderValidatorTestsData.cs
Labels: stable backport

#12443 Check attachment path for null before use
  MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs
Labels: stable backport

#12425 Don't force non-virtual when all episodes in season are isMissing=true
  MediaBrowser.Providers/TV/SeriesMetadataService.cs
Labels: stable backport

#12493 Fix bitstream filter not applied to videos in TS container
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#12490 Set Content-Disposition header to attachment for image endpoints
  Jellyfin.Api/Controllers/ImageController.cs
  Jellyfin.Api/Controllers/PluginsController.cs
  Jellyfin.Api/Controllers/TrickplayController.cs
Labels: stable backport

#12415 Include AVIF extension for support images
  src/Jellyfin.Drawing/ImageProcessor.cs
Labels: stable backport

#12414 Revert "NextUp query respects Limit (#11956)"
  Emby.Server.Implementations/TV/TVSeriesManager.cs
Labels: stable backport

#12499 Apply all codec conditions
  MediaBrowser.Model/Dlna/StreamBuilder.cs
Labels: stable backport

#11250 Fix the broken video orientation (+-90/180)
  Emby.Server.Implementations/Data/SqliteItemRepository.cs
  Jellyfin.Api/Helpers/DynamicHlsHelper.cs
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.Controller/MediaEncoding/FilterOptionType.cs
  MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
  MediaBrowser.MediaEncoding/Probing/MediaStreamInfoSideData.cs
  MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
  MediaBrowser.Model/Entities/MediaStream.cs
  tests/Jellyfin.MediaEncoding.Tests/Probing/ProbeResultNormalizerTests.cs
  tests/Jellyfin.MediaEncoding.Tests/Test Data/Probing/video_metadata.json
Labels: bug, enhancement

#12521 Fix CodecProfiles and video encoder profiles
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.Model/Dlna/StreamBuilder.cs
Labels: stable backport

#12463 Prevent server from starting if the ffmpeg path is invalid
  Emby.Server.Implementations/ApplicationHost.cs
  Emby.Server.Implementations/ConfigurationOptions.cs
  MediaBrowser.Controller/Extensions/ConfigurationExtensions.cs
  MediaBrowser.Controller/MediaEncoding/IMediaEncoder.cs
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
  tests/Jellyfin.Server.Integration.Tests/JellyfinApplicationFactory.cs
Labels: enhancement, backend

#12531 Don't apply chapter image settings to music
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Labels: stable backport

#12540 Tune x264/5 encoding params for realtime playback
  Jellyfin.Api/Controllers/DynamicHlsController.cs
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: enhancement
