Repository jellyfin/jellyfin, pull requests merged in 2024-10, with the labels that each got.

#12824 Don't check remote sources for trickplay
  Jellyfin.Server.Implementations/Trickplay/TrickplayManager.cs
Labels: bug, release critical

#12891 Fix TMDB import failing when no IMDB ID is set for a movie
  CONTRIBUTORS.md
  MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieProvider.cs
Labels: stable backport

#12909 Don't try to prune images for virtual episodes.
  CONTRIBUTORS.md
  MediaBrowser.Providers/Manager/ItemImageProvider.cs
Labels: stable backport

#12915 Fixed possible NullReferenceException in SessionManager
  Emby.Server.Implementations/Session/SessionManager.cs
Labels: bug, stable backport
