Repository jellyfin/jellyfin, pull requests merged in 2024-02, with the labels that each got.

#10888 Feature/ghcs ffmpegversion
  .devcontainer/Dev - Server Ffmpeg/devcontainer.json
  .devcontainer/Dev - Server Ffmpeg/install-ffmpeg.sh
  .vscode/extensions.json
  .vscode/launch.json
  README.md
Labels: enhancement, build, platform

#10884 Extract all subtitle streams simultaneously
  CONTRIBUTORS.md
  MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
Labels: enhancement

#10801 AsyncKeyedLock migration
  CONTRIBUTORS.md
  Directory.Packages.props
  Emby.Server.Implementations/Library/MediaSourceManager.cs
  Jellyfin.Api/Controllers/DynamicHlsController.cs
  Jellyfin.Api/Helpers/FileStreamResponseHelpers.cs
  Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj
  Jellyfin.Server.Implementations/Trickplay/TrickplayManager.cs
  MediaBrowser.Controller/MediaEncoding/ITranscodeManager.cs
  MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
  MediaBrowser.MediaEncoding/MediaBrowser.MediaEncoding.csproj
  MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs
  MediaBrowser.MediaEncoding/Transcoding/TranscodeManager.cs
  src/Jellyfin.Drawing/ImageProcessor.cs
  src/Jellyfin.Drawing/Jellyfin.Drawing.csproj
  src/Jellyfin.LiveTv/Channels/ChannelManager.cs
  src/Jellyfin.LiveTv/EmbyTV/EmbyTV.cs
  src/Jellyfin.LiveTv/Jellyfin.LiveTv.csproj
  src/Jellyfin.LiveTv/Listings/SchedulesDirect.cs
Labels: enhancement, good first issue, backend

#10951 Live TV DI
  Emby.Server.Implementations/ApplicationHost.cs
  MediaBrowser.Controller/LiveTv/ILiveTvManager.cs
  src/Jellyfin.LiveTv/EmbyTV/EmbyTV.cs
  src/Jellyfin.LiveTv/Extensions/LiveTvServiceCollectionExtensions.cs
  src/Jellyfin.LiveTv/LiveTvManager.cs
Labels: breaking change: plugin api

#10968 Correct VIDEO-RANGE field for HLG content
  Jellyfin.Api/Helpers/DynamicHlsHelper.cs
Labels: enhancement

#10976 Replace IServerEntryPoint with IHostedService
  Emby.Server.Implementations/ApplicationHost.cs
  Emby.Server.Implementations/EntryPoints/LibraryChangedNotifier.cs
  Emby.Server.Implementations/EntryPoints/UserDataChangeNotifier.cs
  Emby.Server.Implementations/IO/LibraryMonitor.cs
  Emby.Server.Implementations/IO/LibraryMonitorStartup.cs
  Jellyfin.Server.Implementations/Users/DeviceAccessEntryPoint.cs
  Jellyfin.Server.Implementations/Users/DeviceAccessHost.cs
  Jellyfin.Server/Startup.cs
  MediaBrowser.Controller/Library/ILibraryMonitor.cs
  MediaBrowser.Controller/Plugins/IRunBeforeStartup.cs
  MediaBrowser.Controller/Plugins/IServerEntryPoint.cs
  MediaBrowser.XbmcMetadata/EntryPoint.cs
  MediaBrowser.XbmcMetadata/NfoUserDataSaver.cs
  src/Jellyfin.LiveTv/EmbyTV/EntryPoint.cs
  src/Jellyfin.LiveTv/EmbyTV/LiveTvHost.cs
  src/Jellyfin.LiveTv/RecordingNotifier.cs
  src/Jellyfin.Networking/PortForwardingHost.cs
Labels: breaking change: plugin api

#10772 Discard WebM if there is an unsupported codec
  MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
  tests/Jellyfin.MediaEncoding.Tests/Probing/ProbeResultNormalizerTests.cs
  tests/Jellyfin.MediaEncoding.Tests/Test Data/Probing/video_webm.json
Labels: bug

#10997 Add icon for Jellyfin Windows build
  Jellyfin.Server/Jellyfin.Server.csproj
  Jellyfin.Server/Jellyfin.Server.ico
Labels: ui & ux

#11034 Fix the preproc filters for dvbsub burn-in
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: bug, enhancement

#10691 fix replace missing metadata for music
  MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
Labels: bug, backend
