Repository jellyfin/jellyfin, pull requests merged in 2024-11, with the labels that each got.

#12931 Set AudioCodec when building stream
  MediaBrowser.Model/Dlna/StreamBuilder.cs
Labels: stable backport

#12940 Remove DynamicImageResponse local image after saved to metadata folder
  Emby.Server.Implementations/Images/BaseDynamicImageProvider.cs
  MediaBrowser.Controller/Providers/IProviderManager.cs
  MediaBrowser.Providers/Manager/ItemImageProvider.cs
  MediaBrowser.Providers/Manager/ProviderManager.cs
  tests/Jellyfin.Providers.Tests/Manager/ItemImageProviderTests.cs
Labels: stable backport

#12947 Add a small tolerance value to remux fps check
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#12949 Fix json array string writer in JsonDelimitedArrayConverter
  src/Jellyfin.Extensions/Json/Converters/JsonDelimitedArrayConverter.cs
Labels: stable backport

#12962 Always consider null char as delimiter for ID3v2
  MediaBrowser.Model/Extensions/LibraryOptionsExtension.cs
Labels: stable backport

#12955 Fix trickplay images never being replaced
  Jellyfin.Api/Controllers/ItemRefreshController.cs
Labels: stable backport

#12989 Fix InvariantCulture in VPP tonemap options
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#13030 Always cleanup trickplay temp for ffmpeg failures
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Labels: stable backport

#13003 Only set first MusicBrainz ID for audio tags
  MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
Labels: stable backport

#13026 Fix missing procamp vaapi filter
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#13033 Respect cancellation token/HTTP request aborts correctly in `SymlinkFollowingPhysicalFileResultExecutor`
  Jellyfin.Server/Infrastructure/SymlinkFollowingPhysicalFileResultExecutor.cs
Labels: stable backport

#12916 Added query filter to disregard disabled Providers
  Jellyfin.Api/Controllers/MediaSegmentsController.cs
  Jellyfin.Server.Implementations/MediaSegments/MediaSegmentManager.cs
  MediaBrowser.Controller/MediaSegements/IMediaSegmentManager.cs
Labels: enhancement, stable backport

#13059 Exclude file system based library playlists from migration
  Emby.Server.Implementations/Library/Resolvers/PlaylistResolver.cs
  Jellyfin.Server/Migrations/Routines/RemoveDuplicatePlaylistChildren.cs
Labels: stable backport

#13097 Fix typo in LibraryOptions
  Jellyfin.Server.Implementations/MediaSegments/MediaSegmentManager.cs
  MediaBrowser.Model/Configuration/LibraryOptions.cs
Labels: bug, breaking change: web api

#13113 Only do DoVi remux when the client supports profiles without fallbacks
  Jellyfin.Api/Controllers/DynamicHlsController.cs
Labels: stable backport
