Repository jellyfin/jellyfin, pull requests merged in 2024-12, with the labels that each got.

#13139 Fix missing ConfigureAwait
  MediaBrowser.Providers/Manager/ProviderManager.cs
Labels: stable backport

#13127 Fallback to lossy audio codec for bitrate limit
  Jellyfin.Api/Helpers/StreamingHelpers.cs
Labels: stable backport

#12783 Implement TaskTriggerInfoType enum
  Emby.Server.Implementations/ScheduledTasks/ScheduledTaskWorker.cs
  Emby.Server.Implementations/ScheduledTasks/Tasks/AudioNormalizationTask.cs
  Emby.Server.Implementations/ScheduledTasks/Tasks/ChapterImagesTask.cs
  Emby.Server.Implementations/ScheduledTasks/Tasks/CleanupCollectionAndPlaylistPathsTask.cs
  Emby.Server.Implementations/ScheduledTasks/Tasks/DeleteCacheFileTask.cs
  Emby.Server.Implementations/ScheduledTasks/Tasks/DeleteLogFileTask.cs
  Emby.Server.Implementations/ScheduledTasks/Tasks/DeleteTranscodeFileTask.cs
  Emby.Server.Implementations/ScheduledTasks/Tasks/MediaSegmentExtractionTask.cs
  Emby.Server.Implementations/ScheduledTasks/Tasks/OptimizeDatabaseTask.cs
  Emby.Server.Implementations/ScheduledTasks/Tasks/PeopleValidationTask.cs
  Emby.Server.Implementations/ScheduledTasks/Tasks/PluginUpdateTask.cs
  Emby.Server.Implementations/ScheduledTasks/Tasks/RefreshMediaLibraryTask.cs
  MediaBrowser.Model/Tasks/TaskTriggerInfo.cs
  MediaBrowser.Model/Tasks/TaskTriggerInfoType.cs
  MediaBrowser.Providers/Lyric/LyricScheduledTask.cs
  MediaBrowser.Providers/MediaInfo/SubtitleScheduledTask.cs
  MediaBrowser.Providers/Trickplay/TrickplayImagesTask.cs
  src/Jellyfin.LiveTv/Channels/RefreshChannelsScheduledTask.cs
  src/Jellyfin.LiveTv/Guide/RefreshGuideScheduledTask.cs
Labels: breaking change: plugin api

#13169 Check if the video has an audio track before codec fallback
  Jellyfin.Api/Helpers/StreamingHelpers.cs
Labels: stable backport

#13187 Properly check LAN IP in HasRemoteAccess
  src/Jellyfin.Networking/Manager/NetworkManager.cs
Labels: stable backport

#13195 Migrate rulesets to .editorconf
  .editorconfig
  Directory.Build.props
  Jellyfin.sln
  MediaBrowser.Providers/MediaBrowser.Providers.csproj
  jellyfin.ruleset
  tests/Directory.Build.props
  tests/jellyfin-tests.ruleset
Labels: bug, confirmed

#13182 Don't fall back to ffprobe results for multi-value audio tags
  MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
Labels: stable backport

#13262 Don't use custom params on ultrafast x265 preset
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#13151 Always do tone-mapping for HDR transcoding when software pipeline is used
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#13227 Fix EPG image caching
  src/Jellyfin.LiveTv/Guide/GuideManager.cs
  src/Jellyfin.LiveTv/Listings/SchedulesDirect.cs
Labels: stable backport

#13167 Fix NFO ID parsing
  MediaBrowser.XbmcMetadata/Parsers/MovieNfoParser.cs
  MediaBrowser.XbmcMetadata/Parsers/SeriesNfoParser.cs
Labels: stable backport

#13218 Fix missing episode removal
  MediaBrowser.Providers/TV/SeriesMetadataService.cs
Labels: stable backport

#13288 Fix DTS in HLS
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.Model/Dlna/StreamBuilder.cs
Labels: stable backport

#13209 Transcode to audio codec satisfied other conditions when copy check failed.
  MediaBrowser.Model/Dlna/StreamBuilder.cs
  MediaBrowser.Model/Dlna/TranscodingProfile.cs
Labels: stable backport

#13183 Don't generate trickplay for backdrops
  Jellyfin.Server.Implementations/Trickplay/TrickplayManager.cs
Labels: stable backport
