Repository jellyfin/jellyfin, pull requests merged in 2024-06, with the labels that each got.

#11910 Audio normalization: parse ffmpeg output line by line
  Emby.Server.Implementations/ScheduledTasks/Tasks/AudioNormalizationTask.cs
  src/Jellyfin.Extensions/StreamExtensions.cs
Labels: stable backport

#11873 Fix FirstTimeSetupHandler allowing public access
  Jellyfin.Api/Auth/FirstTimeSetupPolicy/FirstTimeSetupHandler.cs
  tests/Jellyfin.Api.Tests/Auth/FirstTimeSetupPolicy/FirstTimeSetupHandlerTests.cs
Labels: bug, regression, security, stable backport

#11719 Move NFO series season name parsing to own local provider
  Emby.Server.Implementations/Library/Resolvers/TV/SeasonResolver.cs
  MediaBrowser.Controller/Entities/TV/Series.cs
  MediaBrowser.Controller/Providers/ItemInfo.cs
  MediaBrowser.Providers/TV/SeriesMetadataService.cs
  MediaBrowser.XbmcMetadata/Parsers/SeriesNfoParser.cs
  MediaBrowser.XbmcMetadata/Parsers/SeriesNfoSeasonParser.cs
  MediaBrowser.XbmcMetadata/Providers/BaseNfoProvider.cs
  MediaBrowser.XbmcMetadata/Providers/SeriesNfoSeasonProvider.cs
Labels: stable backport

#11762 Mark Audio as RequiresDeserialization and backfill data
  Emby.Server.Implementations/Data/SqliteItemRepository.cs
  Jellyfin.Server/Migrations/MigrationRunner.cs
  Jellyfin.Server/Migrations/Routines/FixAudioData.cs
  MediaBrowser.Controller/Entities/InternalItemsQuery.cs
Labels: regression, stable backport

#11823 Add Env Var to disable second level cache
  Emby.Server.Implementations/ConfigurationOptions.cs
  Jellyfin.Server.Implementations/Extensions/ServiceCollectionExtensions.cs
  Jellyfin.Server/Extensions/WebHostBuilderExtensions.cs
  Jellyfin.Server/Startup.cs
  MediaBrowser.Controller/Extensions/ConfigurationExtensions.cs
Labels: stable backport

#11743 Fix replace logic
  Emby.Server.Implementations/Data/SqliteItemRepository.cs
  Emby.Server.Implementations/Library/LibraryManager.cs
  Jellyfin.Api/Controllers/ItemUpdateController.cs
  MediaBrowser.Controller/Entities/BaseItem.cs
  MediaBrowser.Controller/Entities/Movies/Movie.cs
  MediaBrowser.Controller/Entities/TV/Series.cs
  MediaBrowser.Controller/Entities/Trailer.cs
  MediaBrowser.Providers/Manager/MetadataService.cs
  MediaBrowser.Providers/Movies/MovieMetadataService.cs
  MediaBrowser.Providers/Movies/TrailerMetadataService.cs
  MediaBrowser.Providers/Music/AlbumMetadataService.cs
  MediaBrowser.Providers/Music/AudioMetadataService.cs
  MediaBrowser.Providers/Music/MusicVideoMetadataService.cs
  MediaBrowser.Providers/Playlists/PlaylistMetadataService.cs
  MediaBrowser.Providers/TV/SeriesMetadataService.cs
  tests/Jellyfin.Providers.Tests/Manager/MetadataServiceTests.cs
Labels: stable backport

#11933 Check trailer distinction by URL
  MediaBrowser.Providers/Manager/MetadataService.cs
Labels: stable backport

#11920 Only set season path if season folder parsing was successful
  Emby.Server.Implementations/Library/Resolvers/TV/SeasonResolver.cs
Labels: stable backport

#11954 Do not delete file locations for virtual episodes and seasons
  MediaBrowser.Providers/TV/SeriesMetadataService.cs
Labels: stable backport

#11958 Export trailer URLs in new format
  MediaBrowser.XbmcMetadata/Savers/BaseNfoSaver.cs
Labels: stable backport

#11943 Increase lyrics migration batch size to 5000
  Jellyfin.Server/Migrations/Routines/FixAudioData.cs
Labels: stable backport

#11935 Fix dateadded and movie NFO recognition
  MediaBrowser.Providers/Manager/MetadataService.cs
  MediaBrowser.XbmcMetadata/Savers/MovieNfoSaver.cs
  tests/Jellyfin.XbmcMetadata.Tests/Location/MovieNfoLocationTests.cs
Labels: stable backport

#11934 Fix local image saving
  MediaBrowser.Controller/Providers/DirectoryService.cs
  MediaBrowser.Controller/Providers/IDirectoryService.cs
  MediaBrowser.LocalMetadata/Images/EpisodeLocalImageProvider.cs
  MediaBrowser.Providers/Manager/ImageSaver.cs
  MediaBrowser.Providers/Manager/ItemImageProvider.cs
Labels: stable backport

#11969 Create readonly DB connections when possible
  Emby.Server.Implementations/Data/BaseSqliteRepository.cs
  Emby.Server.Implementations/Data/SqliteItemRepository.cs
  Emby.Server.Implementations/Data/SqliteUserDataRepository.cs
Labels: stable backport

#11921 Fix identify over NFO and replace all when NFO saving enabled
  MediaBrowser.Controller/Providers/IProviderManager.cs
  MediaBrowser.Providers/Manager/ItemImageProvider.cs
  MediaBrowser.Providers/Manager/MetadataService.cs
  MediaBrowser.Providers/Manager/ProviderManager.cs
  tests/Jellyfin.Providers.Tests/Manager/ItemImageProviderTests.cs
Labels: stable backport

#11963 Fix Library renaming
  Emby.Server.Implementations/Library/LibraryManager.cs
  Jellyfin.Api/Controllers/LibraryStructureController.cs
  MediaBrowser.Controller/Library/ILibraryManager.cs
Labels: stable backport

#11978 Fallback to local dir when saving to media dir fails
  MediaBrowser.Providers/Manager/ImageSaver.cs
Labels: stable backport

#11984 Set ProductionLocations instead of Tags
  MediaBrowser.Providers/Manager/MetadataService.cs
Labels: stable backport

#11986 Use only 1 write connection/DB
  Emby.Server.Implementations/Data/BaseSqliteRepository.cs
  Emby.Server.Implementations/Data/ManagedConnection.cs
  Emby.Server.Implementations/Data/SqliteItemRepository.cs
  Emby.Server.Implementations/Data/SqliteUserDataRepository.cs
Labels: stable backport, needs testing

#11959 Do not stop validation if folder was removed
  MediaBrowser.Controller/Entities/Folder.cs
Labels: stable backport

#12037 Do not fail user deletion if we have no playlist folder
  Emby.Server.Implementations/Playlists/PlaylistManager.cs
Labels: stable backport

#12046 Fix mpeg-ts detection
  MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
Labels: stable backport

#12073 Fix Music Brainz release group query
  MediaBrowser.Providers/Plugins/MusicBrainz/MusicBrainzAlbumProvider.cs
Labels: stable backport

#12028 Fix replace all and respect metadata settings
  Jellyfin.Api/Controllers/ItemRefreshController.cs
  MediaBrowser.Providers/Manager/MetadataService.cs
Labels: stable backport

#12031 Fix video embedded image detection
  MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
Labels: stable backport

#12039 Fix local episode image thumb recognition
  MediaBrowser.LocalMetadata/Images/EpisodeLocalImageProvider.cs
Labels: stable backport

#12026 Check hearing impared flags with equality instead of contains
  Emby.Naming/ExternalFiles/ExternalPathParser.cs
  tests/Jellyfin.Naming.Tests/ExternalFiles/ExternalPathParserTests.cs
Labels: stable backport

#12017 Overwrite supported codecs for livetv
  Jellyfin.Api/Helpers/StreamingHelpers.cs
Labels: stable backport

#12065 Make m2ts extension case-insensitive
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Labels: stable backport

#12120 Do not override <year> if <releasedate> is set
  MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs
Labels: stable backport

#12094 Map IPv6 mapped IPv4 addresses back to IPv4 before running checks
  src/Jellyfin.Networking/Manager/NetworkManager.cs
Labels: stable backport

#12043 Fix the Australian PG rating
  Emby.Server.Implementations/Localization/Ratings/au.csv
Labels: stable backport

#12123 Fix Cleanup Task metadata saving
  Emby.Server.Implementations/ScheduledTasks/Tasks/CleanupCollectionAndPlaylistPathsTask.cs
Labels: stable backport

#12149 Fix MicroDVD being recognized as DVDSUB subtitles
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
  MediaBrowser.Model/Entities/MediaStream.cs
Labels: stable backport

#12024 Remove incomplete mediatype restriction from playlists
  Emby.Server.Implementations/Playlists/PlaylistManager.cs
  MediaBrowser.Controller/Playlists/Playlist.cs
Labels: stable backport

#12134 Only cleanup children on specific exceptions
  MediaBrowser.Controller/Entities/Folder.cs
Labels: stable backport

#12050 Fix season handling
  MediaBrowser.Controller/Entities/TV/Series.cs
  MediaBrowser.Providers/TV/SeriesMetadataService.cs
Labels: stable backport

#12053 Rewrite PlaylistItemsProvider as ILocalMetadataProvider
  MediaBrowser.Providers/Playlists/PlaylistItemsProvider.cs
Labels: stable backport

#12025 Fix empty image folder removal for legacy locations
  Emby.Server.Implementations/IO/ManagedFileSystem.cs
  Emby.Server.Implementations/Library/LibraryManager.cs
  Emby.Server.Implementations/ScheduledTasks/Tasks/DeleteCacheFileTask.cs
  Emby.Server.Implementations/ScheduledTasks/Tasks/DeleteTranscodeFileTask.cs
  MediaBrowser.Controller/Entities/BaseItem.cs
  MediaBrowser.Controller/IO/FileSystemHelper.cs
  MediaBrowser.Providers/Manager/ImageSaver.cs
  MediaBrowser.Providers/Manager/ItemImageProvider.cs
  MediaBrowser.Providers/Manager/MetadataService.cs
Labels: stable backport

#12055 Fix season backdrops
  MediaBrowser.Providers/Manager/ImageSaver.cs
  MediaBrowser.Providers/Manager/ItemImageProvider.cs
  MediaBrowser.Providers/Manager/MetadataService.cs
Labels: stable backport

#12126 Try to add extracted lyrics during scanning
  MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
Labels: stable backport

#12166 Fix HDR detection for 4K Blu-Ray BDMVs
  MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs
Labels: stable backport

#11911 Log album name and id in normalization task
  Emby.Server.Implementations/ScheduledTasks/Tasks/AudioNormalizationTask.cs
Labels: stable backport
