Repository jellyfin/jellyfin, pull requests merged in 2024-05, with the labels that each got.

#11472 Fix missing season Index
  MediaBrowser.Providers/Manager/MetadataService.cs
  MediaBrowser.Providers/TV/SeriesMetadataService.cs
Labels: release critical

#11444 Validate Collection Folders on adding and removal
  Emby.Server.Implementations/Library/LibraryManager.cs
  MediaBrowser.Controller/Entities/AggregateFolder.cs
  MediaBrowser.Controller/Entities/Folder.cs
Labels: release critical

#11480 Fix external LRC files being incorrectly overwritten during the initial scan
  MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
Labels: release critical

#11487 Playlist fixes
  Emby.Server.Implementations/Playlists/PlaylistManager.cs
  Jellyfin.Api/Controllers/PlaylistsController.cs
  MediaBrowser.Controller/Playlists/IPlaylistManager.cs
  MediaBrowser.Providers/Playlists/PlaylistItemsProvider.cs
Labels: release critical

#11506 Fix broken hardware encoder and filter for trickplay
  MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Labels: bug

#11504 Let AutoDiscoveryHost bind to all addresses
  src/Jellyfin.Networking/AutoDiscoveryHost.cs
Labels: bug, regression, release critical

#11541 Fix migration with special Rating
  Emby.Server.Implementations/Localization/LocalizationManager.cs
  tests/Jellyfin.Server.Implementations.Tests/Localization/LocalizationManagerTests.cs
Labels: stable backport

#11539 Add metrics collector to disposable parts
  Emby.Server.Implementations/ApplicationHost.cs
  Jellyfin.Server/Program.cs
Labels: stable backport

#11570 Fix absolute path checking on windows
  Emby.Server.Implementations/IO/ManagedFileSystem.cs
  tests/Jellyfin.Server.Implementations.Tests/IO/ManagedFileSystemTests.cs
Labels: bug, stable backport

#11569 Default to processor count concurrent scan instead of 2 * processor count
  MediaBrowser.Controller/Entities/Folder.cs
Labels: enhancement, stable backport

#11578 Change "try" to "attempt" english translation
  Emby.Server.Implementations/Localization/Core/en-US.json
Labels: enhancement, stable backport

#11587 Fix network config
  src/Jellyfin.Networking/Manager/NetworkManager.cs
Labels: bug, stable backport

#11530 Fix reference to deprecated package
  Directory.Packages.props
  MediaBrowser.Model/MediaBrowser.Model.csproj
Labels: merge conflict

#11629 Fix missing filename for timer
  src/Jellyfin.LiveTv/Timers/TimerManager.cs
Labels: bug, stable backport

#11651 Fix FirstTimeSetupPolicy allowing guest access
  Jellyfin.Api/Auth/FirstTimeSetupPolicy/FirstTimeSetupHandler.cs
  tests/Jellyfin.Api.Tests/Auth/FirstTimeSetupPolicy/FirstTimeSetupHandlerTests.cs
Labels: bug, regression, security, stable backport

#11633 Allow empty user id when getting device list
  Jellyfin.Server.Implementations/Devices/DeviceManager.cs
Labels: bug, stable backport

#11653 Don't generate TrickPlay images for files that don't exist
  Jellyfin.Server.Implementations/Trickplay/TrickplayManager.cs
Labels: stable backport

#11668 Always fallback for failed HEAD request
  src/Jellyfin.LiveTv/TunerHosts/M3UTunerHost.cs
Labels: stable backport

#11677 Properly dispose dbContext in MigrateUserDb
  Jellyfin.Server/Migrations/Routines/MigrateUserDb.cs
Labels: bug, stable backport

#11675 Fix quality parameter for vaapi_mjpeg
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Labels: bug, stable backport

#11670 Restore caching for UserManager
  Jellyfin.Server.Implementations/Users/UserManager.cs
Labels: stable backport

#11648 Fix series status parsing
  Emby.Naming/TV/TvParserHelpers.cs
  MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbSeriesProvider.cs
  MediaBrowser.XbmcMetadata/Parsers/SeriesNfoParser.cs
  tests/Jellyfin.Naming.Tests/TV/TvParserHelpersTest.cs
Labels: enhancement, stable backport

#11673 Fix local playlist scanning
  Emby.Server.Implementations/Images/BaseFolderImageProvider.cs
  Emby.Server.Implementations/Images/MusicAlbumImageProvider.cs
  MediaBrowser.Controller/Entities/Audio/MusicAlbum.cs
  MediaBrowser.Providers/Manager/MetadataService.cs
  MediaBrowser.Providers/Playlists/PlaylistItemsProvider.cs
Labels: bug, stable backport

#11698 Fix not binding to SQL parameters
  Emby.Server.Implementations/Data/SqliteItemRepository.cs
Labels: bug, stable backport

#11689 Workaround ffmpeg keyframe seeking for external subtitles
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#11671 Fix network binding
  Jellyfin.Server/Extensions/WebHostBuilderExtensions.cs
  src/Jellyfin.Networking/Manager/NetworkManager.cs
Labels: bug, stable backport

#11699 Use MediaType instead of ToString and add text/ as disallowed mimetypes
  src/Jellyfin.LiveTv/TunerHosts/M3UTunerHost.cs
Labels: bug, stable backport

#11647 Fix season names
  Emby.Server.Implementations/Library/Resolvers/TV/SeasonResolver.cs
  MediaBrowser.Controller/Entities/TV/Series.cs
  MediaBrowser.Providers/TV/SeriesMetadataService.cs
  MediaBrowser.XbmcMetadata/Parsers/SeriesNfoParser.cs
Labels: bug, stable backport

#11680 Secure local playlist path handling
  MediaBrowser.Providers/Playlists/PlaylistItemsProvider.cs
Labels: bug, stable backport

#11700 Prevent double iterating over all seasons
  MediaBrowser.Providers/TV/SeriesMetadataService.cs
Labels: stable backport

#11733 Fix OpenAPI workflow
  .github/workflows/ci-openapi.yml
Labels: bug, security, ci

#11738 Don't require user when getting current session
  Jellyfin.Api/Helpers/RequestHelpers.cs
Labels: bug, stable backport

#11739 Do not run trickplay on scan if disabled
  MediaBrowser.Providers/Trickplay/TrickplayProvider.cs
Labels: bug, stable backport

#11713 Fix VideoToolbox H264 constrained profile option
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#11774 Apply audio boost when downmixing regardless of downmixalgo
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#11772 Prefer profile over codec for display title
  MediaBrowser.Model/Entities/MediaStream.cs
Labels: enhancement

#11788 Override too small trickplay image interval
  Jellyfin.Server.Implementations/Trickplay/TrickplayManager.cs
Labels: stable backport

#11781 Retain order blu-ray segments
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Labels: stable backport

#11799 Disable VA-VK interop on not supported kernel versions
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#11802 Mark SearchHint.MatchedTerm as nullable
  MediaBrowser.Model/Search/SearchHint.cs
Labels: stable backport

#11754 Fix BD/DVD folder chapter image extraction
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.Controller/MediaEncoding/IMediaEncoder.cs
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Labels: regression, stable backport

#11798 Recalculate trickplay image height for anamorphic videos
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Labels: stable backport

#11808 Add Canceled to ended state
  Emby.Naming/TV/TvParserHelpers.cs
Labels: stable backport

#11804 Exclude virtual items from DateLastMediaAdded calculation
  MediaBrowser.Providers/Manager/MetadataService.cs
Labels: stable backport

#11801 Force more compatible transcoding profile for LiveTV
  Jellyfin.Api/Helpers/MediaInfoHelper.cs
Labels: stable backport

#11792 Improve reliability of HasChanged check
  MediaBrowser.Providers/MediaInfo/ProbeProvider.cs
Labels: stable backport

#11790 Trickplay: kill ffmpeg when task is cancelled
  CONTRIBUTORS.md
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Labels: stable backport

#11830 Fix the IOSurf error in QSV transcoding
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#11805 Use SharedStream for LiveTV more restrictively
  src/Jellyfin.LiveTv/TunerHosts/M3UTunerHost.cs
Labels: stable backport, needs testing

#11766 Filter invalid IPs on external interface matching
  MediaBrowser.Common/Net/NetworkConstants.cs
  src/Jellyfin.Networking/Manager/NetworkManager.cs
Labels: stable backport

#11812 Extract media attachment one by one if the filename appears to be a path
  MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs
Labels: stable backport

#11857 Fix ffprobe -user_agent parameter
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
  tests/Jellyfin.MediaEncoding.Tests/Probing/ProbeExternalSourcesTests.cs
Labels: stable backport

#11876 Don't check if admin has access to library when updating
  Jellyfin.Api/Controllers/LibraryStructureController.cs
Labels: stable backport

#11806 Return missing episodes for series when no user defined
  Emby.Server.Implementations/Session/SessionManager.cs
  Jellyfin.Api/Controllers/TvShowsController.cs
  MediaBrowser.Controller/Entities/TV/Season.cs
  MediaBrowser.Controller/Entities/TV/Series.cs
  MediaBrowser.Providers/TV/SeriesMetadataService.cs
Labels: stable backport

#11882 Fix missing episodes query for seasons
  MediaBrowser.Controller/Entities/TV/Series.cs
Labels: stable backport

#11894 Escape tmpConcatPath for DVD and BD folder
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#11859 Use music metadata from ffprobe when TagLib fails
  MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
Labels: stable backport

#11886 Fix multi-part album folder being detected as artist folder
  Emby.Server.Implementations/Library/Resolvers/Audio/MusicArtistResolver.cs
Labels: stable backport

#11851 Relax remuxing requirement for LiveTV
  Jellyfin.Api/Helpers/MediaInfoHelper.cs
  Jellyfin.Api/Helpers/StreamingHelpers.cs
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport
