Repository jellyfin/jellyfin, pull requests merged in 2025-02, with the labels that each got.

#13448 Fix interface ordering again
  src/Jellyfin.Networking/Manager/NetworkManager.cs
Labels: stable backport

#13459 Fixed Websocket not locking state correctly
  Emby.Server.Implementations/Session/WebSocketController.cs
Labels: bug, backend, stable backport

#13439 Fall back to calculating mime type from path when needed
  MediaBrowser.Providers/Manager/ItemImageProvider.cs
  MediaBrowser.Providers/Manager/ProviderManager.cs
Labels: stable backport

#13490 Correctly handle audio number tag fallbacks
  MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
Labels: stable backport

#13504 Fix LiveTV Guide Backdrop image not updating
  src/Jellyfin.LiveTv/Guide/GuideManager.cs
Labels: stable backport

#13469 Fix SchedulesDirect image prefetching
  src/Jellyfin.LiveTv/Guide/GuideManager.cs
Labels: stable backport

#12721 Skip allowed tags check for parents of an item
  MediaBrowser.Controller/Channels/Channel.cs
  MediaBrowser.Controller/Entities/BaseItem.cs
  MediaBrowser.Controller/Entities/CollectionFolder.cs
  MediaBrowser.Controller/Entities/Folder.cs
  MediaBrowser.Controller/Entities/Movies/BoxSet.cs
  MediaBrowser.Controller/Playlists/Playlist.cs
Labels: stable backport

#13532 Fix image encoding concurrency limit
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
  src/Jellyfin.Drawing/ImageProcessor.cs
Labels: stable backport

#13396 Make the JsonConverters for delimited arrays more generic
  Jellyfin.Api/Controllers/ArtistsController.cs
  Jellyfin.Api/Controllers/ChannelsController.cs
  Jellyfin.Api/Controllers/CollectionController.cs
  Jellyfin.Api/Controllers/FilterController.cs
  Jellyfin.Api/Controllers/GenresController.cs
  Jellyfin.Api/Controllers/InstantMixController.cs
  Jellyfin.Api/Controllers/ItemsController.cs
  Jellyfin.Api/Controllers/LibraryController.cs
  Jellyfin.Api/Controllers/LibraryStructureController.cs
  Jellyfin.Api/Controllers/LiveTvController.cs
  Jellyfin.Api/Controllers/MoviesController.cs
  Jellyfin.Api/Controllers/MusicGenresController.cs
  Jellyfin.Api/Controllers/PersonsController.cs
  Jellyfin.Api/Controllers/PlaylistsController.cs
  Jellyfin.Api/Controllers/SearchController.cs
  Jellyfin.Api/Controllers/SessionController.cs
  Jellyfin.Api/Controllers/StudiosController.cs
  Jellyfin.Api/Controllers/SuggestionsController.cs
  Jellyfin.Api/Controllers/TrailersController.cs
  Jellyfin.Api/Controllers/TvShowsController.cs
  Jellyfin.Api/Controllers/UniversalAudioController.cs
  Jellyfin.Api/Controllers/UserLibraryController.cs
  Jellyfin.Api/Controllers/UserViewsController.cs
  Jellyfin.Api/Controllers/VideosController.cs
  Jellyfin.Api/Controllers/YearsController.cs
  Jellyfin.Api/ModelBinders/CommaDelimitedCollectionModelBinder.cs
  Jellyfin.Api/ModelBinders/PipeDelimitedCollectionModelBinder.cs
  Jellyfin.Api/Models/LiveTvDtos/GetProgramsDto.cs
  Jellyfin.Api/Models/PlaylistDtos/CreatePlaylistDto.cs
  Jellyfin.Api/Models/PlaylistDtos/UpdatePlaylistDto.cs
  MediaBrowser.Model/Dto/ClientCapabilitiesDto.cs
  src/Jellyfin.Extensions/Json/Converters/JsonCommaDelimitedArrayConverter.cs
  src/Jellyfin.Extensions/Json/Converters/JsonCommaDelimitedCollectionConverter.cs
  src/Jellyfin.Extensions/Json/Converters/JsonCommaDelimitedCollectionConverterFactory.cs
  src/Jellyfin.Extensions/Json/Converters/JsonDelimitedCollectionConverter.cs
  src/Jellyfin.Extensions/Json/Converters/JsonPipeDelimitedCollectionConverter.cs
  src/Jellyfin.Extensions/Json/Converters/JsonPipeDelimitedCollectionConverterFactory.cs
  tests/Jellyfin.Api.Tests/ModelBinders/CommaDelimitedCollectionModelBinderTests.cs
  tests/Jellyfin.Api.Tests/ModelBinders/PipeDelimitedCollectionModelBinderTests.cs
  tests/Jellyfin.Extensions.Tests/Json/Converters/JsonCommaDelimitedCollectionTests.cs
  tests/Jellyfin.Extensions.Tests/Json/Converters/JsonCommaDelimitedIReadOnlyListTests.cs
  tests/Jellyfin.Extensions.Tests/Json/Models/GenericBodyIReadOnlyCollectionModel.cs
  tests/Jellyfin.Extensions.Tests/Json/Models/GenericBodyIReadOnlyListModel.cs
  tests/Jellyfin.Extensions.Tests/Json/Models/GenericBodyListModel.cs
Labels: needs testing

#13556 Don't allow usernames to have leading or trailing spaces
  Jellyfin.Server.Implementations/Users/UserManager.cs
  tests/Jellyfin.Server.Implementations.Tests/Users/UserManagerTests.cs
Labels: requires-web

#13611 Remove empty ParentIndexNumber workaround
  Emby.Server.Implementations/Library/LibraryManager.cs
  MediaBrowser.Providers/Plugins/Omdb/OmdbEpisodeProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbEpisodeImageProvider.cs
  MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbEpisodeProvider.cs
Labels: stable backport

#13593 Wait for ffmpeg to exit on Windows before we try deleting the concat file
  Emby.Server.Implementations/ScheduledTasks/Tasks/AudioNormalizationTask.cs
Labels: stable backport

#13601 Delete children from cache on parent delete
  Emby.Server.Implementations/Library/LibraryManager.cs
Labels: stable backport
