Repository jellyfin/jellyfin, pull requests merged in 2025-01, with the labels that each got.

#13313 Use nv15 as intermediate format for 2-pass rkrga scaling
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: stable backport

#13345 Never treat matroska as webm for audio playback
  MediaBrowser.Model/Dlna/StreamBuilder.cs
Labels: stable backport

#12970 Add ability to remove a ChannelMapping
  src/Jellyfin.LiveTv/Listings/ListingsManager.cs
Labels: needs testing, live-tv

#13388 Fix rating levels
  Emby.Server.Implementations/Localization/Ratings/br.csv
  Emby.Server.Implementations/Localization/Ratings/ca.csv
  Emby.Server.Implementations/Localization/Ratings/es.csv
  Emby.Server.Implementations/Localization/Ratings/gb.csv
  Emby.Server.Implementations/Localization/Ratings/ie.csv
  Emby.Server.Implementations/Localization/Ratings/no.csv
  Emby.Server.Implementations/Localization/Ratings/nz.csv
  Emby.Server.Implementations/Localization/Ratings/us.csv
  Jellyfin.Server/Migrations/Routines/MigrateRatingLevels.cs
  tests/Jellyfin.Server.Implementations.Tests/Localization/LocalizationManagerTests.cs
Labels: stable backport

#13382 Fix interface selection
  src/Jellyfin.Networking/Manager/NetworkManager.cs
Labels: stable backport

#13092 Fix: handling of <set> elements in NfoParser
  MediaBrowser.XbmcMetadata/Parsers/MovieNfoParser.cs
  MediaBrowser.XbmcMetadata/Savers/MovieNfoSaver.cs
  tests/Jellyfin.XbmcMetadata.Tests/Parsers/MovieNfoParserTests.cs
  tests/Jellyfin.XbmcMetadata.Tests/Test Data/Lilo & Stitch.nfo
Labels: stable backport

#13390 Catch IOExceptions for GetFileSystemMetadata
  Emby.Server.Implementations/IO/ManagedFileSystem.cs
Labels: stable backport

#13411 Use WriteThrough for ImageSaver
  MediaBrowser.Providers/Manager/ImageSaver.cs
Labels: stable backport

#13384 Fix parallel use of not thread-safe SubtitleFormat instance
  MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs
Labels: stable backport

#13425 Open files with FileShare.Read for BlurHash calculations
  Directory.Packages.props
  src/Jellyfin.Drawing.Skia/SkiaEncoder.cs
Labels: stable backport

#13222 Remove the ability to auto port forward
  Directory.Packages.props
  Jellyfin.Api/Controllers/StartupController.cs
  Jellyfin.Api/Models/StartupDtos/StartupRemoteAccessDto.cs
  Jellyfin.Server/Migrations/PreStartupRoutines/MigrateNetworkConfiguration.cs
  Jellyfin.Server/Startup.cs
  MediaBrowser.Common/Net/NetworkConfiguration.cs
  jellyfin.code-workspace
  src/Jellyfin.Networking/Jellyfin.Networking.csproj
  src/Jellyfin.Networking/PortForwardingHost.cs
Labels: release-highlight, requires-web

#13423 Don't select audio stream and codec explicitly for copy when bitrate exceeds limit
  MediaBrowser.Model/Dlna/StreamBuilder.cs
Labels: stable backport
