Repository jellyfin/jellyfin, pull requests merged in 2025-04, with the labels that each got.

#13822 Add missing public properties to SystemInfo response
  Emby.Server.Implementations/SystemManager.cs
Labels: enhancement

#13277 Improve dynamic HDR metadata handling
  Jellyfin.Api/Controllers/DynamicHlsController.cs
  Jellyfin.Api/Helpers/DynamicHlsHelper.cs
  Jellyfin.Data/Enums/VideoRangeType.cs
  Jellyfin.Server.Implementations/Item/MediaStreamRepository.cs
  MediaBrowser.Controller/MediaEncoding/BitStreamFilterOptionType.cs
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.Controller/MediaEncoding/EncodingJobInfo.cs
  MediaBrowser.Controller/MediaEncoding/IMediaEncoder.cs
  MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
  MediaBrowser.MediaEncoding/Probing/InternalMediaInfoResult.cs
  MediaBrowser.MediaEncoding/Probing/MediaFrameInfo.cs
  MediaBrowser.MediaEncoding/Probing/MediaFrameSideDataInfo.cs
  MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
  MediaBrowser.Model/Dlna/ConditionProcessor.cs
  MediaBrowser.Model/Dlna/StreamInfo.cs
  MediaBrowser.Model/Entities/MediaStream.cs
  src/Jellyfin.Database/Jellyfin.Database.Implementations/Entities/MediaStreamInfo.cs
  src/Jellyfin.Database/Jellyfin.Database.Providers.Sqlite/Migrations/20250327171413_AddHdr10PlusFlag.Designer.cs
  src/Jellyfin.Database/Jellyfin.Database.Providers.Sqlite/Migrations/20250327171413_AddHdr10PlusFlag.cs
  src/Jellyfin.Database/Jellyfin.Database.Providers.Sqlite/Migrations/JellyfinDbModelSnapshot.cs
Labels: feature

#13901 Add ServerName to startup configuration
  Jellyfin.Api/Controllers/StartupController.cs
  Jellyfin.Api/Models/StartupDtos/StartupConfigurationDto.cs
  tests/Jellyfin.Server.Integration.Tests/Controllers/StartupControllerTests.cs
Labels: enhancement

#13904 Remove the hashed password from startup users response
  Jellyfin.Api/Controllers/StartupController.cs
  tests/Jellyfin.Server.Integration.Tests/Controllers/StartupControllerTests.cs
Labels: bug

#13911 Add DoVi Profile 5 support for Rockchip RKMPP
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Labels: enhancement

#13378 Only run merge conflict labler action on pull requests
  .github/workflows/pull-request-conflict.yml
Labels: github-actions

#13906 Add .gitignore style ignoring
  Directory.Packages.props
  Emby.Server.Implementations/Emby.Server.Implementations.csproj
  Emby.Server.Implementations/Library/CoreResolutionIgnoreRule.cs
  Emby.Server.Implementations/Library/DotIgnoreIgnoreRule.cs
  Emby.Server.Implementations/Library/IgnorePatterns.cs
  Emby.Server.Implementations/Library/LibraryManager.cs
  tests/Jellyfin.Server.Implementations.Tests/Library/DotIgnoreIgnoreRuleTest.cs
Labels: release-highlight
