Repository jellyfin/jellyfin, pull requests merged in 2025-03, with the labels that each got.

#13492 Don't use RETURNING clause with EFCore
  Jellyfin.Server.Implementations/JellyfinDbContext.cs
Labels: needs testing

#13618 Include Role and SortOrder in MergePeople to fix "Search for missing metadata"
  MediaBrowser.Providers/Manager/MetadataService.cs
Labels: stable backport

#13639 Support more rating formats
  Emby.Server.Implementations/Localization/LocalizationManager.cs
  tests/Jellyfin.Server.Implementations.Tests/Localization/LocalizationManagerTests.cs
Labels: stable backport

#13659 Upgrade LrcParser to 2025.228.1
  Directory.Packages.props
Labels: stable backport

#12907 Fix stackoverflow in MediaSourceCount
  MediaBrowser.Controller/Entities/Video.cs
Labels: bug

#13694 Clone fallback audio tags instead of use ATL.Track.set
  MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
Labels: stable backport

#13720 Fix regression where "Search for missing metadata" not handling cast having multiple roles
  MediaBrowser.Providers/Manager/MetadataService.cs
Labels: stable backport

#12492 Fix only returning one item from /Item/Latest api.
  Emby.Server.Implementations/Library/LibraryManager.cs
  Emby.Server.Implementations/Library/UserViewManager.cs
  Jellyfin.Server.Implementations/Item/BaseItemRepository.cs
  MediaBrowser.Controller/Library/ILibraryManager.cs
  MediaBrowser.Controller/Persistence/IItemRepository.cs
Labels: enhancement

#9369 Reduce allocations, simplifed code, faster implementation, included tests - StreamInfo.ToUrl
  Jellyfin.Api/Helpers/MediaInfoHelper.cs
  MediaBrowser.Model/Dlna/StreamBuilder.cs
  MediaBrowser.Model/Dlna/StreamInfo.cs
  MediaBrowser.Model/Dto/MediaSourceInfo.cs
  src/Jellyfin.Extensions/EnumerableExtensions.cs
  tests/Jellyfin.Model.Tests/Dlna/LegacyStreamInfo.cs
  tests/Jellyfin.Model.Tests/Dlna/StreamBuilderTests.cs
  tests/Jellyfin.Model.Tests/Dlna/StreamInfoTests.cs
Labels: enhancement, backend

#13194 Enable VideoToolbox AV1 decode
  MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
  MediaBrowser.Controller/MediaEncoding/IMediaEncoder.cs
  MediaBrowser.MediaEncoding/Encoder/ApplePlatformHelper.cs
  MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
  MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Labels: feature

#5366 Reduce Skia conversions
  src/Jellyfin.Drawing.Skia/SkiaEncoder.cs
  src/Jellyfin.Drawing.Skia/StripCollageBuilder.cs
Labels: confirmed, dependencies
